"""Build ten original, unreviewed, bounded conversation rehearsals.

These rehearsals extend the named topic without changing its original text.
The fixed replies introduce any additional fictional details explicitly.
Run from any directory; no network or model calls are made.
"""
from __future__ import annotations

import json
from pathlib import Path


def loc(nl: str, en: str, fa: str) -> dict[str, str]:
    return {"nl": nl, "en": en, "fa": fa}


def choice(key: str, label: dict, aliases: list[str], valid: bool) -> dict:
    return {"id": key.replace("_", "-"), "label": label, "aliases": aliases, "valid": valid}


def step(key, goal, cue, hint, accepted, groups, example, choices=None):
    return {
        "id": key.replace("_", "-"), "goal": goal, "cue": cue, "hint": hint,
        "accepted": accepted, "required_groups": groups,
        "choices": choices or [], "example": example,
    }


def conversation(stage, number, title, role, setup, opening, success, steps):
    topic = f"{stage}-t{number:03d}"
    return {
        "id": f"{topic}-conversation", "stage_id": stage, "topic_id": topic,
        "title": title, "role": role, "setup": setup, "opening": opening,
        "success": success, "steps": steps,
    }


CONVERSATIONS = [
    conversation(
        "a1", 4,
        loc("Op bezoek bij de buur", "Visiting your neighbour", "دیدار با همسایه"),
        loc("Amir, uw nieuwe buur", "Amir, your new neighbour", "امیر، همسایهٔ جدید شما"),
        loc("U ontmoet Amir aan de deur. Stel u voor en spreek een kort bezoek af. In dit oefengesprek woont Amir op nummer acht. Hij is zaterdag om drie uur thuis, maar niet om twee uur.",
            "You meet Amir at the door. Introduce yourself and arrange a short visit. In this rehearsal, Amir lives at number eight. He is home on Saturday at three, but not at two.",
            "امیر را دم در می‌بینید. خودتان را معرفی کنید و برای یک دیدار کوتاه قرار بگذارید. در این تمرین، امیر در پلاک هشت زندگی می‌کند. شنبه ساعت سه خانه است، اما ساعت دو نیست."),
        loc("Dag, ik ben Amir, uw nieuwe buur. Hoe heet u?", "Hello, I'm Amir, your new neighbour. What's your name?", "سلام، من امیر هستم، همسایهٔ جدید شما. اسم شما چیست؟"),
        loc("Tot zaterdag om drie uur, op nummer acht!", "See you on Saturday at three, at number eight!", "تا شنبه ساعت سه، در پلاک هشت!"),
        [
            step("introduce",
                 loc("Begroet Amir en stel uzelf voor.", "Greet Amir and introduce yourself.", "به امیر سلام کنید و خودتان را معرفی کنید."),
                 loc("Dag, ik ben Amir. Hoe heet u?", "Hello, I'm Amir. What's your name?", "سلام، من امیر هستم. اسم شما چیست؟"),
                 loc("Begin met ‘Dag’ of ‘Hallo’. Zeg daarna uw naam.", "Start with ‘Dag’ or ‘Hallo’, then say your name.", "با «Dag» یا «Hallo» شروع کنید، سپس نامتان را بگویید."),
                 loc("Aangenaam! Welkom in de straat.", "Nice to meet you! Welcome to the street.", "خوشوقتم! به محله خوش آمدید."),
                 [["dag", "hallo", "goeiemorgen", "goedemorgen", "goeienavond", "goedenavond"], ["ik ben", "mijn naam is", "ik heet"]],
                 loc("Dag, ik ben Noor.", "Hello, I'm Noor.", "سلام، من نور هستم.")),
            step("visit_day",
                 loc("Vraag of u zaterdag op bezoek mag komen.", "Ask whether you may visit on Saturday.", "بپرسید آیا می‌توانید شنبه به دیدنش بروید."),
                 loc("Kom gerust eens langs. Op welke dag wilt u komen?", "You're welcome to visit. Which day would you like to come?", "خوشحال می‌شوم سر بزنید. چه روزی می‌خواهید بیایید؟"),
                 loc("U kunt vragen: ‘Mag ik … komen?’", "You can ask: ‘Mag ik … komen?’", "می‌توانید بپرسید: «Mag ik … komen?»"),
                 loc("Zaterdag past.", "Saturday works.", "شنبه مناسب است."),
                 [["komen", "kom", "langs", "bezoek"]],
                 loc("Mag ik zaterdag komen?", "May I come on Saturday?", "می‌توانم شنبه بیایم؟"),
                 [choice("saturday", loc("Zaterdag", "Saturday", "شنبه"), ["zaterdag"], True), choice("sunday", loc("Zondag", "Sunday", "یکشنبه"), ["zondag"], False)]),
            step("confirm_visit",
                 loc("Bevestig het juiste uur en huisnummer.", "Confirm the correct time and house number.", "ساعت و پلاک درست را تأیید کنید."),
                 loc("Om twee uur ben ik weg. Om drie uur ben ik thuis, op nummer acht. Wanneer komt u en waar?", "I'm out at two. I'm home at three, at number eight. When and where will you come?", "ساعت دو بیرون هستم. ساعت سه در خانه، پلاک هشت، هستم. چه ساعتی و کجا می‌آیید؟"),
                 loc("Zeg: ‘Dan kom ik om … naar nummer …’", "Say: ‘Dan kom ik om … naar nummer …’", "بگویید: «Dan kom ik om … naar nummer …»"),
                 loc("Dat klopt. Het bezoek is afgesproken.", "That's right. The visit is arranged.", "درست است. قرار دیدار مشخص شد."),
                 [["nummer acht", "nummer 8", "huisnummer acht", "huisnummer 8"]],
                 loc("Dan kom ik zaterdag om drie uur naar nummer acht.", "Then I'll come on Saturday at three to number eight.", "پس شنبه ساعت سه به پلاک هشت می‌آیم."),
                 [choice("three", loc("Drie uur", "Three o'clock", "ساعت سه"), ["drie uur", "om drie", "15 uur", "15.00"], True), choice("two", loc("Twee uur", "Two o'clock", "ساعت دو"), ["twee uur", "om twee", "14 uur", "14.00"], False)]),
        ],
    ),
    conversation(
        "a1", 19,
        loc("Het juiste spoor vragen", "Asking for the right platform", "پرسیدن سکوی درست"),
        loc("Een medewerker in het station", "A station employee", "کارمند ایستگاه"),
        loc("U wilt met de trein naar Gent. Vraag waar u moet zijn. Oefen ook hoe u om herhaling vraagt. De trein in dit verzonnen gesprek vertrekt van spoor drie en heeft tien minuten vertraging.",
            "You want to take a train to Ghent. Ask where to go and practise asking for repetition. The train in this fictional conversation leaves from platform three and is ten minutes late.",
            "می‌خواهید با قطار به خنت بروید. بپرسید کجا باید بروید و درخواست تکرار را هم تمرین کنید. قطار این گفت‌وگوی خیالی از سکوی سه حرکت می‌کند و ده دقیقه تأخیر دارد."),
        loc("Goedemorgen. Kan ik u helpen?", "Good morning. Can I help you?", "صبح بخیر. می‌توانم کمکتان کنم؟"),
        loc("Juist, spoor drie. Goede reis!", "That's right, platform three. Have a good journey!", "درست است، سکوی سه. سفر خوبی داشته باشید!"),
        [
            step("ask_platform",
                 loc("Noem Gent en vraag naar het spoor.", "Mention Ghent and ask for the platform.", "نام خنت را بگویید و سکو را بپرسید."),
                 loc("Waar wilt u naartoe?", "Where would you like to go?", "می‌خواهید کجا بروید؟"),
                 loc("U kunt beginnen: ‘Ik wil naar Gent. Waar …?’", "You can start: ‘Ik wil naar Gent. Waar …?’", "می‌توانید شروع کنید: «Ik wil naar Gent. Waar …?»"),
                 loc("De trein naar Gent vertrekt van spoor drie.", "The train to Ghent leaves from platform three.", "قطار خنت از سکوی سه حرکت می‌کند."),
                 [["gent"], ["waar", "welk", "welke"]],
                 loc("Ik wil naar Gent. Van welk spoor vertrekt de trein?", "I want to go to Ghent. Which platform does the train leave from?", "می‌خواهم به خنت بروم. قطار از کدام سکو حرکت می‌کند؟")),
            step("ask_repeat",
                 loc("Vraag om herhaling of om trager te spreken.", "Ask for repetition or slower speech.", "درخواست تکرار کنید یا بخواهید آهسته‌تر صحبت کند."),
                 loc("Er is ook tien minuten vertraging. Ik sprak wat snel. Wat kunt u vragen als u het niet begrijpt?", "There is also a ten-minute delay. I spoke rather quickly. What can you ask if you don't understand?", "ده دقیقه تأخیر هم دارد. کمی سریع صحبت کردم. اگر متوجه نشدید، چه می‌توانید بپرسید؟"),
                 loc("Probeer: ‘Kunt u dat …?’", "Try: ‘Kunt u dat …?’", "امتحان کنید: «Kunt u dat …?»"),
                 loc("Natuurlijk. Ik zeg het nog eens.", "Of course. I'll say it again.", "البته. دوباره می‌گویم."),
                 [["herhalen", "nog eens", "opnieuw", "trager", "langzamer", "langzaam"]],
                 loc("Kunt u dat even herhalen, alstublieft?", "Could you repeat that, please?", "ممکن است لطفاً آن را تکرار کنید؟")),
            step("confirm_platform",
                 loc("Zeg naar welk spoor u gaat.", "Say which platform you will go to.", "بگویید به کدام سکو می‌روید."),
                 loc("Spoor drie. Tien minuten vertraging. Naar welk spoor gaat u nu?", "Platform three. Ten minutes late. Which platform will you go to now?", "سکوی سه. ده دقیقه تأخیر. حالا به کدام سکو می‌روید؟"),
                 loc("Zeg: ‘Ik ga naar spoor …’", "Say: ‘Ik ga naar spoor …’", "بگویید: «Ik ga naar spoor …»"),
                 loc("U hebt het juiste spoor begrepen.", "You understood the correct platform.", "سکوی درست را فهمیدید."),
                 [["spoor", "perron"]],
                 loc("Ik ga naar spoor drie.", "I'll go to platform three.", "به سکوی سه می‌روم."),
                 [choice("platform_three", loc("Spoor drie", "Platform three", "سکوی سه"), ["spoor drie", "spoor 3", "perron drie", "perron 3"], True), choice("platform_one", loc("Spoor één", "Platform one", "سکوی یک"), ["spoor een", "spoor één", "spoor 1", "perron een", "perron één", "perron 1"], False)]),
        ],
    ),
    conversation(
        "a1", 26,
        loc("Een vraag in de les", "Asking a question in class", "پرسیدن سؤال در کلاس"),
        loc("Uw leerkracht", "Your teacher", "معلم شما"),
        loc("U zit in de les. U werkt op bladzijde zes en hebt een potlood nodig. In dit nieuwe oefengesprek leent de leerkracht u een potlood. U geeft het na de les terug.",
            "You are in class, working on page six, and need a pencil. In this new rehearsal, the teacher lends you a pencil. You return it after class.",
            "در کلاس هستید، روی صفحهٔ شش کار می‌کنید و به مداد نیاز دارید. در این تمرین جدید، معلم به شما مداد قرض می‌دهد. پس از کلاس آن را پس می‌دهید."),
        loc("Welkom. Open uw boek op bladzijde zes.", "Welcome. Open your book at page six.", "خوش آمدید. کتابتان را در صفحهٔ شش باز کنید."),
        loc("Goed afgesproken. Veel succes met de oefening!", "Agreed. Good luck with the exercise!", "قرارمان مشخص شد. در تمرین موفق باشید!"),
        [
            step("check_page",
                 loc("Vraag of bladzijde zes juist is.", "Check whether page six is correct.", "بپرسید آیا صفحهٔ شش درست است."),
                 loc("Op welke bladzijde begint u? Controleer het even bij mij.", "Which page will you start on? Check with me.", "از کدام صفحه شروع می‌کنید؟ از من بپرسید تا مطمئن شوید."),
                 loc("U kunt vragen: ‘Is bladzijde … juist?’", "You can ask: ‘Is bladzijde … juist?’", "می‌توانید بپرسید: «Is bladzijde … juist?»"),
                 loc("Ja, bladzijde zes is juist.", "Yes, page six is correct.", "بله، صفحهٔ شش درست است."),
                 [["juist", "klopt", "bedoelt", "bedoel", "zes?", "6?"]],
                 loc("Is bladzijde zes juist?", "Is page six correct?", "آیا صفحهٔ شش درست است؟"),
                 [choice("six", loc("Bladzijde zes", "Page six", "صفحهٔ شش"), ["bladzijde zes", "bladzijde 6", "pagina zes", "pagina 6"], True), choice("seven", loc("Bladzijde zeven", "Page seven", "صفحهٔ هفت"), ["bladzijde zeven", "bladzijde 7", "pagina zeven", "pagina 7"], False)]),
            step("borrow_pencil",
                 loc("Vraag beleefd om een potlood.", "Politely ask for a pencil.", "مؤدبانه مداد بخواهید."),
                 loc("Vandaag schrijven we met potlood. U hebt geen potlood bij. Wat vraagt u?", "Today we write in pencil. You haven't brought one. What do you ask?", "امروز با مداد می‌نویسیم. شما مداد همراه ندارید. چه می‌پرسید؟"),
                 loc("Begin met ‘Mag ik’ of ‘Kan ik’.", "Start with ‘Mag ik’ or ‘Kan ik’.", "با «Mag ik» یا «Kan ik» شروع کنید."),
                 loc("Natuurlijk, u mag dit potlood lenen.", "Of course, you may borrow this pencil.", "البته، می‌توانید این مداد را قرض بگیرید."),
                 [["potlood"], ["mag ik", "kan ik", "kunt u", "alstublieft", "graag"]],
                 loc("Mag ik een potlood lenen, alstublieft?", "May I borrow a pencil, please?", "می‌توانم لطفاً یک مداد قرض بگیرم؟")),
            step("return_pencil",
                 loc("Bedank de leerkracht en zeg wanneer u het teruggeeft.", "Thank the teacher and say when you will return it.", "از معلم تشکر کنید و بگویید چه وقت مداد را پس می‌دهید."),
                 loc("Ik heb het potlood na de les weer nodig. Wat spreken we af?", "I need the pencil back after class. What shall we agree?", "بعد از کلاس دوباره به مداد نیاز دارم. چه قراری می‌گذاریم؟"),
                 loc("‘Dank u. Ik geef het … terug.’", "‘Dank u. Ik geef het … terug.’", "«Dank u. Ik geef het … terug.»"),
                 loc("Dank u, dan krijg ik het na de les terug.", "Thank you, then I'll get it back after class.", "متشکرم، پس بعد از کلاس آن را پس می‌گیرم."),
                 [["dank", "bedankt", "merci"], ["terug"]],
                 loc("Dank u. Ik geef het na de les terug.", "Thank you. I'll return it after class.", "متشکرم. بعد از کلاس آن را پس می‌دهم."),
                 [choice("after_class", loc("Na de les", "After class", "بعد از کلاس"), ["na de les", "na deze les"], True), choice("tomorrow", loc("Morgen", "Tomorrow", "فردا"), ["morgen"], False)]),
        ],
    ),
    conversation(
        "a2", 2,
        loc("De datum controleren", "Checking the date", "بررسی تاریخ"),
        loc("De onthaalmedewerker voor een gesprek", "The receptionist arranging a meeting", "مسئول پذیرش برای هماهنگی جلسه"),
        loc("In uw uitnodiging staat donderdag, in de bevestiging vrijdag. Bel om de datum te controleren. Voor deze fictieve afspraak neemt u uw contract en een kopie van uw diploma mee. De kopie moet u vooraf maken; de kopieermachine ter plaatse is stuk.",
            "Your invitation says Thursday, but the confirmation says Friday. Call to check the date. For this fictional meeting, bring your contract and a copy of your diploma. Make the copy beforehand: the copier at the meeting location is broken.",
            "در دعوت‌نامه پنجشنبه نوشته شده، اما تأییدیه جمعه را نشان می‌دهد. برای بررسی تاریخ تماس بگیرید. برای این قرار خیالی، قرارداد و کپی مدرکتان را ببرید. کپی را از قبل آماده کنید؛ دستگاه کپی محل جلسه خراب است."),
        loc("Goedendag, waarmee kan ik u helpen?", "Hello, how can I help you?", "سلام، چطور می‌توانم کمکتان کنم؟"),
        loc("Dan verwachten we u vrijdag, met uw contract en de vooraf gemaakte kopie. Tot dan!", "Then we expect you on Friday, with your contract and the copy made beforehand. See you then!", "پس جمعه با قرارداد و کپی‌ای که از قبل آماده کرده‌اید منتظرتان هستیم. تا آن روز!"),
        [
            step("check_dates",
                 loc("Leg uit dat u twee verschillende dagen hebt gekregen en vraag welke juist is.", "Explain that you received two different days and ask which is correct.", "توضیح دهید دو روز متفاوت به شما اعلام شده و بپرسید کدام درست است."),
                 loc("Welke informatie wilt u controleren?", "Which information would you like to check?", "می‌خواهید کدام اطلاعات را بررسی کنید؟"),
                 loc("Noem donderdag én vrijdag. Vraag: ‘Welke dag is juist?’", "Mention both Thursday and Friday. Ask: ‘Welke dag is juist?’", "هم پنجشنبه و هم جمعه را نام ببرید. بپرسید: «Welke dag is juist?»"),
                 loc("Vrijdag is juist. De uitnodiging bevatte een fout.", "Friday is correct. The invitation contained a mistake.", "جمعه درست است. در دعوت‌نامه اشتباه شده بود."),
                 [["donderdag"], ["vrijdag"], ["welke", "juist", "klopt"]],
                 loc("De uitnodiging zegt donderdag en de bevestiging vrijdag. Welke dag is juist?", "The invitation says Thursday and the confirmation says Friday. Which day is correct?", "در دعوت‌نامه پنجشنبه و در تأییدیه جمعه نوشته شده. کدام روز درست است؟")),
            step("confirm_documents",
                 loc("Bevestig vrijdag en noem beide documenten die u meebrengt.", "Confirm Friday and name both documents you will bring.", "جمعه را تأیید کنید و هر دو مدرکی را که می‌برید نام ببرید."),
                 loc("Het gesprek is vrijdag. Breng uw contract en een kopie van uw diploma mee. Kunt u dat bevestigen?", "The meeting is Friday. Bring your contract and a copy of your diploma. Can you confirm that?", "جلسه جمعه است. قرارداد و کپی مدرکتان را بیاورید. می‌توانید تأیید کنید؟"),
                 loc("‘Ik kom vrijdag en breng … mee.’ Vergeet de kopie niet.", "‘Ik kom vrijdag en breng … mee.’ Don't forget the copy.", "«Ik kom vrijdag en breng … mee.» کپی را فراموش نکنید."),
                 loc("Goed, u hebt de dag en de documenten bevestigd.", "Good, you confirmed the day and the documents.", "خوب است، روز و مدارک را تأیید کردید."),
                 [["vrijdag"], ["contract"], ["diploma", "diplomakopie"]],
                 loc("Ik kom vrijdag en breng mijn contract en een kopie van mijn diploma mee.", "I'll come on Friday and bring my contract and a copy of my diploma.", "جمعه می‌آیم و قرارداد و کپی مدرکم را می‌آورم.")),
            step("copy_beforehand",
                 loc("Zeg dat u de kopie vooraf maakt.", "Say that you will make the copy beforehand.", "بگویید کپی را از قبل آماده می‌کنید."),
                 loc("Nog iets: onze kopieermachine is stuk. Wanneer maakt u de kopie?", "One more thing: our copier is broken. When will you make the copy?", "یک نکتهٔ دیگر: دستگاه کپی ما خراب است. چه وقت کپی را آماده می‌کنید؟"),
                 loc("Gebruik ‘vooraf’ of ‘op voorhand’.", "Use ‘vooraf’ or ‘op voorhand’.", "از «vooraf» یا «op voorhand» استفاده کنید."),
                 loc("Prima, zo is alles klaar voor u vertrekt.", "Good, then everything will be ready before you leave.", "خوب است، پس پیش از حرکت همه‌چیز آماده خواهد بود."),
                 [["kopie", "kopiëren", "kopieer"]],
                 loc("Ik maak de kopie vooraf en breng ze vrijdag mee.", "I'll make the copy beforehand and bring it on Friday.", "کپی را از قبل آماده می‌کنم و جمعه با خودم می‌آورم."),
                 [choice("beforehand", loc("Vooraf", "Beforehand", "از قبل"), ["vooraf", "op voorhand", "van tevoren", "voor ik kom", "vóór ik kom", "thuis"], True), choice("on_site", loc("Ter plaatse", "At the meeting location", "در محل جلسه"), ["ter plaatse", "bij u", "tijdens het gesprek"], False)]),
        ],
    ),
    conversation(
        "a2", 16,
        loc("Een afspraak in de keuken", "Agreeing where things belong", "هماهنگی در آشپزخانه"),
        loc("Uw huisgenoot", "Your housemate", "هم‌خانهٔ شما"),
        loc("U wilt pasta koken, maar vindt het vergiet niet. Uw huisgenoot weet waar het ligt. Spreek af waar u het na het koken zet en hoe u de anderen verwittigt.",
            "You want to cook pasta but cannot find the colander. Your housemate knows where it is. Agree where to put it after cooking and how to let the others know.",
            "می‌خواهید پاستا بپزید، اما آبکش را پیدا نمی‌کنید. هم‌خانه‌تان می‌داند کجاست. هماهنگ کنید بعد از آشپزی کجا قرارش دهید و چطور به دیگران اطلاع دهید."),
        loc("Dag! Zoek je iets in de keuken?", "Hi! Are you looking for something in the kitchen?", "سلام! در آشپزخانه دنبال چیزی می‌گردی؟"),
        loc("Afgesproken: het vergiet komt vooraan en de anderen krijgen bericht.", "Agreed: the colander goes at the front and the others will be told.", "قرار شد: آبکش جلو قرار می‌گیرد و به بقیه اطلاع می‌دهید."),
        [
            step("ask_location",
                 loc("Vraag waar het vergiet is.", "Ask where the colander is.", "بپرسید آبکش کجاست."),
                 loc("Wat zoek je precies?", "What exactly are you looking for?", "دقیقاً دنبال چه چیزی می‌گردی؟"),
                 loc("‘Weet je waar …?’", "‘Weet je waar …?’", "«Weet je waar …?»"),
                 loc("Het vergiet ligt in de onderste kast, achter de kommen.", "The colander is in the bottom cupboard, behind the bowls.", "آبکش در کابینت پایینی، پشت کاسه‌هاست."),
                 [["vergiet"], ["waar"]],
                 loc("Weet je waar het vergiet is?", "Do you know where the colander is?", "می‌دانی آبکش کجاست؟")),
            step("check_location",
                 loc("Herhaal waar het vergiet nu ligt.", "Repeat where the colander is now.", "تکرار کنید آبکش الان کجاست."),
                 loc("Kon je me verstaan? In welke kast en achter wat moet je zoeken?", "Could you hear me? Which cupboard, and behind what, should you look?", "صدایم را شنیدی؟ در کدام کابینت و پشت چه چیزی باید بگردی؟"),
                 loc("Noem ‘de onderste kast’ en ‘de kommen’.", "Mention ‘de onderste kast’ and ‘de kommen’.", "از «de onderste kast» و «de kommen» استفاده کنید."),
                 loc("Juist, daar ligt het.", "That's right, it's there.", "درست است، همان‌جاست."),
                 [["onderste kast", "kast onderaan"], ["achter de kommen", "achter die kommen"]],
                 loc("Het ligt in de onderste kast, achter de kommen.", "It's in the bottom cupboard, behind the bowls.", "در کابینت پایینی، پشت کاسه‌هاست.")),
            step("new_location",
                 loc("Beloof het vooraan te zetten en de anderen te verwittigen.", "Promise to put it at the front and tell the others.", "قول دهید آن را جلو بگذارید و به بقیه خبر بدهید."),
                 loc("Achteraan ziet niemand het. Zet het na het koken vooraan in dezelfde kast. Hoe weten de anderen dat?", "Nobody sees it at the back. Put it at the front of the same cupboard after cooking. How will the others know?", "عقب باشد کسی آن را نمی‌بیند. بعد از آشپزی آن را جلوی همان کابینت بگذار. دیگران چطور باخبر شوند؟"),
                 loc("‘Ik zet het … en vertel aan de anderen …’", "‘Ik zet het … en vertel aan de anderen …’", "«Ik zet het … en vertel aan de anderen …»"),
                 loc("Dat is een duidelijke afspraak.", "That's a clear agreement.", "توافق روشنی است."),
                 [["vertel", "zeg", "bericht", "laat weten", "verwittig"]],
                 loc("Ik zet het vooraan en vertel aan de anderen waar het staat.", "I'll put it at the front and tell the others where it is.", "آن را جلو می‌گذارم و به بقیه می‌گویم کجاست."),
                 [choice("front", loc("Vooraan", "At the front", "جلو"), ["vooraan", "voor in de kast"], True), choice("back", loc("Achteraan", "At the back", "عقب"), ["achteraan", "achter de kommen", "achter in de kast"], False)]),
        ],
    ),
    conversation(
        "a2", 27,
        loc("Eerst een vraag stellen", "Asking before starting", "پرسیدن پیش از شروع"),
        loc("Een collega op uw eerste werkdag", "A colleague on your first day", "همکار شما در اولین روز کاری"),
        loc("U ziet materiaal dat u nog niet kent, waaronder een veiligheidsgordel. Oefen hoe u om uitleg vraagt en afspreekt om te wachten. Dit gesprek oefent taal; het geeft geen instructies om het materiaal te gebruiken.",
            "You see unfamiliar equipment, including a safety harness. Practise asking for an explanation and agreeing to wait. This conversation practises language; it does not instruct you how to use the equipment.",
            "وسایلی می‌بینید که هنوز با آن‌ها آشنا نیستید، از جمله یک کمربند ایمنی. درخواست توضیح و توافق برای منتظر ماندن را تمرین کنید. این گفت‌وگو برای تمرین زبان است و روش استفاده از وسایل را آموزش نمی‌دهد."),
        loc("Welkom, Amir. Hebt u een vraag voor u begint?", "Welcome, Amir. Do you have a question before starting?", "خوش آمدید، امیر. پیش از شروع سؤالی دارید؟"),
        loc("Afgesproken, u wacht op uitleg. Daarna bespreken we samen wat u mag doen.", "Agreed, you'll wait for an explanation. Then we'll discuss together what you may do.", "قرار شد منتظر توضیح بمانید. بعد با هم دربارهٔ کارهایی که می‌توانید انجام دهید صحبت می‌کنیم."),
        [
            step("ask_explanation",
                 loc("Zeg welk materiaal u niet kent en vraag om uitleg.", "Say which equipment is unfamiliar and ask for an explanation.", "بگویید با کدام وسیله آشنا نیستید و توضیح بخواهید."),
                 loc("Welk materiaal kent u nog niet?", "Which equipment is unfamiliar to you?", "هنوز با کدام وسیله آشنا نیستید؟"),
                 loc("‘Ik ken deze veiligheidsgordel niet. Kunt u …?’", "‘Ik ken deze veiligheidsgordel niet. Kunt u …?’", "«Ik ken deze veiligheidsgordel niet. Kunt u …?»"),
                 loc("Goed dat u het vraagt. We bekijken dat samen.", "Good that you asked. We'll look at it together.", "خوب شد پرسیدید. با هم بررسی‌اش می‌کنیم."),
                 [["veiligheidsgordel", "gordel"], ["uitleg", "uitleggen", "tonen", "helpen"]],
                 loc("Ik ken deze veiligheidsgordel niet. Kunt u uitleg geven?", "I'm not familiar with this safety harness. Can you explain it?", "با این کمربند ایمنی آشنا نیستم. می‌توانید توضیح بدهید؟")),
            step("ask_limits",
                 loc("Vraag welke taken u voorlopig niet alleen mag doen.", "Ask which tasks you may not yet do alone.", "بپرسید فعلاً کدام کارها را نباید به‌تنهایی انجام دهید."),
                 loc("Sommige taken doet u eerst samen met een collega. Welke vraag helpt u om dat te controleren?", "Some tasks must first be done together with a colleague. What question helps you check this?", "بعضی کارها را ابتدا همراه همکار انجام می‌دهید. چه سؤالی به شما کمک می‌کند این موضوع را روشن کنید؟"),
                 loc("Vraag naar ‘welke taken’ en ‘alleen’.", "Ask about ‘welke taken’ and ‘alleen’.", "دربارهٔ «welke taken» و «alleen» بپرسید."),
                 loc("We zullen de taken samen overlopen voor u begint.", "We'll go through the tasks together before you start.", "پیش از شروع، کارها را با هم مرور می‌کنیم."),
                 [["welke taken", "welke taak", "wat mag", "welke klussen"], ["alleen", "zelfstandig"]],
                 loc("Welke taken mag ik voorlopig niet alleen doen?", "Which tasks may I not yet do alone?", "فعلاً کدام کارها را نباید به‌تنهایی انجام دهم؟")),
            step("wait_for_help",
                 loc("Spreek af dat u op uitleg wacht.", "Agree to wait for an explanation.", "توافق کنید منتظر توضیح بمانید."),
                 loc("Ik moet even telefoneren. Ik kom zo terug voor de uitleg. Wat doet u intussen met het onbekende materiaal?", "I need to make a quick call. I'll return shortly to explain. What will you do meanwhile with the unfamiliar equipment?", "باید یک تماس کوتاه بگیرم. زود برمی‌گردم تا توضیح بدهم. تا آن وقت با وسیله‌ای که نمی‌شناسید چه می‌کنید؟"),
                 loc("Begin met ‘Ik wacht …’.", "Start with ‘Ik wacht …’.", "با «Ik wacht …» شروع کنید."),
                 loc("Dank u, we beginnen samen na de uitleg.", "Thank you, we'll start together after the explanation.", "متشکرم، بعد از توضیح با هم شروع می‌کنیم."),
                 [["uitleg", "terug", "helpt", "collega"]],
                 loc("Ik wacht op uw uitleg.", "I'll wait for your explanation.", "منتظر توضیح شما می‌مانم."),
                 [choice("wait", loc("Wachten op uitleg", "Wait for an explanation", "منتظر توضیح ماندن"), ["ik wacht", "wachten op", "wacht tot"], True), choice("start_alone", loc("Zelf beginnen", "Start alone", "به‌تنهایی شروع کردن"), ["ik begin zelf", "ik probeer zelf", "ik gebruik het alvast", "zonder uitleg beginnen"], False)]),
        ],
    ),
    conversation(
        "b1", 34,
        loc("De juiste bijlage opsturen", "Sending the correct attachment", "فرستادن پیوست درست"),
        loc("Een collega die uw verslag nodig heeft", "A colleague who needs your report", "همکاری که به گزارش شما نیاز دارد"),
        loc("U hebt een lege bijlage verstuurd. In deze nieuwe oefensituatie hebt u twee bestanden: versie één is leeg, versie twee hebt u geopend en gecontroleerd. Los de vergissing op en vraag of uw collega het verslag kan lezen. De collega gebruikt nu een telefoon en later een laptop.",
            "You sent an empty attachment. In this new rehearsal, version one is empty; you have opened and checked version two. Resolve the mistake and ask whether your colleague can read the report. They are using a phone now and a laptop later.",
            "پیوست خالی فرستاده‌اید. در این تمرین جدید دو فایل دارید: نسخهٔ یک خالی است؛ نسخهٔ دو را باز و بررسی کرده‌اید. اشتباه را برطرف کنید و بپرسید آیا همکارتان می‌تواند گزارش را بخواند. او اکنون از تلفن و بعداً از لپ‌تاپ استفاده می‌کند."),
        loc("Dag Sara, ik heb uw mail ontvangen, maar de bijlage is leeg.", "Hi Sara, I received your email, but the attachment is empty.", "سلام سارا، ایمیلت را دریافت کردم، اما پیوست خالی است."),
        loc("Afgesproken. Ik controleer straks op mijn laptop of het nieuwe verslag leesbaar is en laat het weten.", "Agreed. I'll check on my laptop later whether the new report is readable and let you know.", "قرار شد. بعداً روی لپ‌تاپ بررسی می‌کنم آیا گزارش جدید خواندنی است و به شما خبر می‌دهم."),
        [
            step("acknowledge_error",
                 loc("Erken dat de bijlage leeg was en bied uw excuses aan.", "Acknowledge the empty attachment and apologise.", "خالی بودن پیوست را بپذیرید و عذرخواهی کنید."),
                 loc("Kunt u uitleggen wat er met de bijlage gebeurd is?", "Can you explain what happened to the attachment?", "می‌توانید توضیح دهید چه اتفاقی برای پیوست افتاده است؟"),
                 loc("‘Sorry, de bijlage was …’", "‘Sorry, de bijlage was …’", "«Sorry, de bijlage was …»"),
                 loc("Dank u voor de verduidelijking.", "Thank you for explaining the mistake.", "ممنون که اشتباه را توضیح دادید."),
                 [["bijlage", "bestand"], ["leeg", "lege"], ["sorry", "excuses", "spijt", "verontschuldig"]],
                 loc("Sorry, ik heb een lege bijlage verstuurd.", "Sorry, I sent an empty attachment.", "ببخشید، یک پیوست خالی فرستادم.")),
            step("choose_version",
                 loc("Zeg welke gecontroleerde versie u nu verstuurt.", "Say which checked version you will now send.", "بگویید اکنون کدام نسخهٔ بررسی‌شده را می‌فرستید."),
                 loc("Er zijn twee versies. Versie één was leeg. Welke stuurt u nu en hebt u die gecontroleerd?", "There are two versions. Version one was empty. Which will you send now, and have you checked it?", "دو نسخه وجود دارد. نسخهٔ یک خالی بود. اکنون کدام را می‌فرستید و آیا بررسی‌اش کرده‌اید؟"),
                 loc("Noem de versie en de controle die u al gedaan hebt.", "Name the version and the check you have already made.", "نسخه و بررسی‌ای را که انجام داده‌اید نام ببرید."),
                 loc("Goed, ik verwacht de gecontroleerde versie.", "Good, I'll look out for the checked version.", "خوب است، منتظر نسخهٔ بررسی‌شده هستم."),
                 [["gecontroleerd", "nagekeken", "geopend"]],
                 loc("Ik stuur versie twee. Ik heb die geopend en gecontroleerd.", "I'll send version two. I have opened and checked it.", "نسخهٔ دو را می‌فرستم. آن را باز و بررسی کرده‌ام."),
                 [choice("version_two", loc("Versie twee", "Version two", "نسخهٔ دو"), ["versie twee", "versie 2", "tweede versie"], True), choice("version_one", loc("Versie één", "Version one", "نسخهٔ یک"), ["versie een", "versie één", "versie 1", "eerste versie"], False)]),
            step("request_confirmation",
                 loc("Vraag om een bevestiging zodra de collega het verslag op de laptop kan controleren.", "Ask for confirmation once your colleague can check the report on their laptop.", "بخواهید وقتی همکار توانست گزارش را روی لپ‌تاپ بررسی کند، تأیید بدهد."),
                 loc("Ik gebruik nu mijn telefoon en kan het nog niet goed controleren. Straks heb ik mijn laptop. Welke bevestiging wilt u dan?", "I'm on my phone and cannot properly check it yet. I'll have my laptop later. What would you like me to confirm then?", "الان با تلفن هستم و هنوز نمی‌توانم خوب بررسی کنم. بعداً لپ‌تاپم را دارم. آن وقت چه چیزی را برایتان تأیید کنم؟"),
                 loc("Vraag of het verslag leesbaar is zodra de laptop beschikbaar is.", "Ask whether the report is readable once the laptop is available.", "بپرسید وقتی لپ‌تاپ در دسترس بود، آیا گزارش خواندنی است."),
                 loc("Duidelijk, ik geef u na die controle een antwoord.", "Understood, I'll reply after checking.", "متوجه شدم، پس از بررسی پاسخ می‌دهم."),
                 [["bevestigen", "laten weten", "controleren", "nakijken"], ["leesbaar", "lezen", "openen", "opent"], ["laptop"]],
                 loc("Kunt u straks op uw laptop controleren of het verslag leesbaar is en mij dat laten weten?", "Could you check later on your laptop whether the report is readable and let me know?", "ممکن است بعداً روی لپ‌تاپ بررسی کنید آیا گزارش خواندنی است و به من خبر بدهید؟")),
        ],
    ),
    conversation(
        "b1", 49,
        loc("Een hemd vergelijken", "Comparing shirts", "مقایسهٔ پیراهن‌ها"),
        loc("Een winkelmedewerker", "A shop assistant", "فروشنده"),
        loc("U past een hemd dat kleiner valt dan u verwachtte. Vraag hulp om de pasvorm te vergelijken. In deze oefensituatie noemt de medewerker de hemden A en B. A knelt aan de schouders; B zit goed en is beschikbaar. Er wordt niets gekocht zonder uw keuze.",
            "You try on a shirt that fits smaller than expected. Ask for help comparing the fit. In this rehearsal, the assistant calls the shirts A and B. A is tight at the shoulders; B fits well and is available. Nothing is bought without your choice.",
            "پیراهنی را امتحان می‌کنید که از انتظار شما کوچک‌تر است. برای مقایسهٔ اندازه کمک بخواهید. در این تمرین، فروشنده پیراهن‌ها را A و B می‌نامد. A در شانه‌ها تنگ است؛ B خوب می‌نشیند و موجود است. بدون انتخاب شما خریدی انجام نمی‌شود."),
        loc("Goedendag. Past het hemd zoals u verwacht had?", "Hello. Does the shirt fit as you expected?", "سلام. پیراهن همان‌طور که انتظار داشتید اندازه است؟"),
        loc("Duidelijk: u kiest hemd B omdat de pasvorm goed is.", "Understood: you choose shirt B because it fits well.", "مشخص شد: پیراهن B را انتخاب می‌کنید چون اندازه‌اش مناسب است."),
        [
            step("explain_fit",
                 loc("Leg uit dat de pasvorm niet bij uw verwachting van de maat past.", "Explain that the fit does not match what you expected from the size.", "توضیح دهید اندازهٔ پیراهن با انتظارتان از سایز آن مطابقت ندارد."),
                 loc("Wat is er precies anders dan u verwachtte?", "What exactly is different from what you expected?", "دقیقاً چه چیزی با انتظارتان فرق دارد؟"),
                 loc("Verbind ‘de maat op het kaartje’ met ‘te klein’ of ‘te strak’.", "Connect ‘de maat op het kaartje’ with ‘te klein’ or ‘te strak’.", "«de maat op het kaartje» را به «te klein» یا «te strak» ربط دهید."),
                 loc("Dan vergelijken we de pasvorm in plaats van alleen het kaartje.", "Then let's compare the fit rather than just the label.", "پس تناسب لباس را بررسی می‌کنیم و فقط به برچسب نگاه نمی‌کنیم."),
                 [["maat", "kaartje"], ["klein", "strak", "krap", "knelt"]],
                 loc("De maat op het kaartje lijkt juist, maar het hemd zit te strak.", "The size on the label seems right, but the shirt is too tight.", "سایز روی برچسب درست به نظر می‌رسد، اما پیراهن خیلی تنگ است.")),
            step("request_comparison",
                 loc("Vraag om de hemden na te meten of hun pasvorm te vergelijken.", "Ask to measure the shirts or compare their fit.", "بخواهید پیراهن‌ها را اندازه بگیرند یا تناسبشان را مقایسه کنند."),
                 loc("De kaartjes tonen dezelfde maat. Hoe kunnen we toch vergelijken wat voor u past?", "The labels show the same size. How can we still compare what fits you?", "برچسب‌ها یک سایز را نشان می‌دهند. چطور می‌توانیم ببینیم کدام اندازهٔ شماست؟"),
                 loc("U kunt vragen: ‘Kunt u … nameten?’", "You can ask: ‘Kunt u … nameten?’", "می‌توانید بپرسید: «Kunt u … nameten?»"),
                 loc("Goed, we bekijken de afmetingen en de pasvorm van beide hemden.", "Good, we'll look at the measurements and fit of both shirts.", "خوب است، اندازه‌ها و تناسب هر دو پیراهن را بررسی می‌کنیم."),
                 [["nameten", "meten", "afmetingen", "vergelijken", "vergelijk"]],
                 loc("Kunt u de hemden nameten en de pasvorm vergelijken?", "Could you measure the shirts and compare their fit?", "می‌توانید پیراهن‌ها را اندازه بگیرید و تناسبشان را مقایسه کنید؟")),
            step("choose_fit",
                 loc("Kies het passende hemd en geef de reden.", "Choose the shirt that fits and give your reason.", "پیراهن مناسب را انتخاب کنید و دلیل بیاورید."),
                 loc("Na het passen blijkt: hemd A knelt aan de schouders, hemd B zit goed. B is beschikbaar. Welk hemd kiest u en waarom?", "After trying them on: shirt A is tight at the shoulders, shirt B fits well. B is available. Which do you choose, and why?", "پس از امتحان: پیراهن A در شانه‌ها تنگ است، پیراهن B خوب اندازه است. B موجود است. کدام را انتخاب می‌کنید و چرا؟"),
                 loc("‘Ik kies hemd …, want …’", "‘Ik kies hemd …, want …’", "«Ik kies hemd …, want …»"),
                 loc("U hebt uw keuze met de pasvorm verbonden.", "You linked your choice to the fit.", "انتخابتان را به تناسب لباس مرتبط کردید."),
                 [["past", "goed", "comfortabel", "ruim"]],
                 loc("Ik kies hemd B, want dat zit goed.", "I'll choose shirt B because it fits well.", "پیراهن B را انتخاب می‌کنم چون خوب اندازه است."),
                 [choice("shirt_b", loc("Hemd B", "Shirt B", "پیراهن B"), ["hemd b", "shirt b", "hemd bee"], True), choice("shirt_a", loc("Hemd A", "Shirt A", "پیراهن A"), ["hemd a", "shirt a"], False)]),
        ],
    ),
    conversation(
        "b2", 3,
        loc("Een werkbare beurtrol", "A workable rota", "برنامهٔ نوبتی عملی"),
        loc("Een collega die het rooster mee opstelt", "A colleague helping prepare the rota", "همکاری که در تنظیم برنامه کمک می‌کند"),
        loc("Het team wil late diensten eerlijker verdelen. Bespreek een nieuwe proefregeling. Iedereen meldt vóór vrijdag echte beperkingen. Voor de proef is Noor dinsdag beschikbaar, maar maandag niet. Privédetails zijn niet nodig. Evalueer de verdeling na twee weken met het team.",
            "The team wants to share late shifts more fairly. Discuss a new trial. Everyone reports genuine availability constraints before Friday. For the trial, Noor is available on Tuesday but not Monday. Private details are unnecessary. Review the distribution with the team after two weeks.",
            "گروه می‌خواهد شیفت‌های دیرهنگام عادلانه‌تر تقسیم شوند. دربارهٔ یک برنامهٔ آزمایشی جدید صحبت کنید. همه پیش از جمعه محدودیت‌های واقعی زمانی‌شان را اعلام می‌کنند. در این آزمایش، نور سه‌شنبه در دسترس است، اما دوشنبه نیست. جزئیات شخصی لازم نیست. پس از دو هفته تقسیم کار را با گروه ارزیابی کنید."),
        loc("We willen een eerlijker rooster. Hoe verzamelen we de beperkingen zonder dat iedereen zijn privéleven moet uitleggen?", "We want a fairer rota. How can we collect constraints without making everyone explain their private lives?", "برنامهٔ عادلانه‌تری می‌خواهیم. چطور محدودیت‌ها را جمع کنیم بدون اینکه همه مجبور شوند زندگی خصوصی‌شان را توضیح دهند؟"),
        loc("We proberen de beurtrol met Noor op dinsdag en bekijken na twee weken samen of de verdeling werkt.", "We'll try the rota with Noor on Tuesday and review together after two weeks whether the distribution works.", "برنامه را با نوبت سه‌شنبهٔ نور امتحان می‌کنیم و پس از دو هفته با هم بررسی می‌کنیم آیا تقسیم کار مناسب است."),
        [
            step("gather_constraints",
                 loc("Stel voor om beperkingen vóór vrijdag te verzamelen, zonder privédetails te vragen.", "Propose gathering constraints before Friday without asking for private details.", "پیشنهاد دهید محدودیت‌ها پیش از جمعه جمع شوند، بدون درخواست جزئیات خصوصی."),
                 loc("Wat vragen we aan het team en tegen wanneer?", "What should we ask the team, and by when?", "از گروه چه می‌خواهیم و تا چه زمانی؟"),
                 loc("Noem de deadline en beperk de vraag tot beschikbaarheid.", "State the deadline and limit the request to availability.", "مهلت را مشخص کنید و درخواست را به زمان در دسترس بودن محدود کنید."),
                 loc("Zo weten we wie wanneer beschikbaar is zonder meer informatie dan nodig te vragen.", "That tells us who is available when without asking for more information than needed.", "این‌طور می‌فهمیم چه کسی چه وقت در دسترس است، بدون درخواست اطلاعات اضافی."),
                 [["voor vrijdag", "vóór vrijdag"], ["beschikbaar", "beschikbaarheid", "beperkingen", "onmogelijk"], ["privé", "privaat", "privédetails", "persoonlijke details"]],
                 loc("Laat iedereen vóór vrijdag zijn beschikbaarheid doorgeven. Privédetails zijn niet nodig om de beperkingen te bespreken.", "Let everyone report availability before Friday. Private details are unnecessary when discussing constraints.", "بگذاریم همه پیش از جمعه زمان در دسترس بودنشان را اعلام کنند. برای صحبت دربارهٔ محدودیت‌ها به جزئیات خصوصی نیازی نیست.")),
            step("respect_constraint",
                 loc("Plan Noor op de beschikbare dag en motiveer uw keuze.", "Schedule Noor on the available day and explain your choice.", "نور را در روزی که در دسترس است برنامه‌ریزی کنید و دلیل بیاورید."),
                 loc("Noor kan maandag niet, maar dinsdag wel. Beide dagen hebben een late dienst. Welke dag kiest u voor Noor en waarom?", "Noor is unavailable on Monday but available on Tuesday. Both days have a late shift. Which day do you choose for Noor, and why?", "نور دوشنبه نمی‌تواند، اما سه‌شنبه می‌تواند. هر دو روز شیفت دیرهنگام دارند. کدام روز را برای نور انتخاب می‌کنید و چرا؟"),
                 loc("Verbind de gekozen dag aan de opgegeven beschikbaarheid.", "Connect the chosen day to the stated availability.", "روز انتخابی را به زمان در دسترس بودن اعلام‌شده ربط دهید."),
                 loc("Dat respecteert de beperking van Noor.", "That respects Noor's constraint.", "این انتخاب محدودیت نور را رعایت می‌کند."),
                 [["kan", "beschikbaar", "mogelijk", "past"]],
                 loc("Ik kies dinsdag voor Noor, omdat ze dan beschikbaar is.", "I choose Tuesday for Noor because she is available then.", "سه‌شنبه را برای نور انتخاب می‌کنم، چون آن روز در دسترس است."),
                 [choice("tuesday", loc("Dinsdag", "Tuesday", "سه‌شنبه"), ["dinsdag"], True), choice("monday", loc("Maandag", "Monday", "دوشنبه"), ["maandag"], False)]),
            step("review_trial",
                 loc("Stel voor om na twee weken met het team te beoordelen of de verdeling eerlijk en haalbaar is.", "Propose reviewing with the team after two weeks whether the distribution is fair and workable.", "پیشنهاد دهید پس از دو هفته با گروه بررسی کنید آیا تقسیم کار عادلانه و عملی است."),
                 loc("Een collega vindt een rooster op papier niet genoeg. Wanneer vragen we het team of de proef echt werkt?", "A colleague says a rota on paper is not enough. When should we ask the team whether the trial really works?", "یکی از همکاران می‌گوید برنامهٔ روی کاغذ کافی نیست. چه وقت از گروه بپرسیم آیا آزمایش واقعاً جواب می‌دهد؟"),
                 loc("Noem ‘na twee weken’, het team en wat u samen controleert.", "Mention ‘na twee weken’, the team and what you will check together.", "«na twee weken»، گروه و چیزی را که با هم بررسی می‌کنید ذکر کنید."),
                 loc("Goed, de proef krijgt een concreet evaluatiemoment.", "Good, the trial has a specific review point.", "خوب است، برای آزمایش زمان مشخصی جهت ارزیابی تعیین شد."),
                 [["team", "collega's", "collega’s", "collega"], ["eerlijk", "haalbaar", "werkt", "werkbaar", "verdeling"]],
                 loc("Na twee weken vragen we het team of de verdeling eerlijk en haalbaar is.", "After two weeks, we'll ask the team whether the distribution is fair and workable.", "پس از دو هفته از گروه می‌پرسیم آیا تقسیم کار عادلانه و عملی است."),
                 [choice("two_weeks", loc("Na twee weken", "After two weeks", "پس از دو هفته"), ["na twee weken", "na 2 weken", "over twee weken", "over 2 weken"], True), choice("no_review", loc("Zonder evaluatie", "Without a review", "بدون ارزیابی"), ["geen evaluatie", "zonder evaluatie", "nooit evalueren"], False)]),
        ],
    ),
    conversation(
        "b2", 14,
        loc("Een zaalregeling uitproberen", "Trying a room-sharing arrangement", "آزمایش برنامهٔ استفادهٔ مشترک از سالن"),
        loc("De beheerder van twee oefenruimtes", "The manager of two rehearsal rooms", "مسئول دو فضای تمرین"),
        loc("Twee verenigingen vragen dezelfde zaal op donderdag. Dit is een nieuwe oefensituatie bij het onderwerp: een dansgroep heeft de grote zaal nodig om te bewegen; een leesgroep kan in de kleine zaal terecht. De kleine zaal is beschikbaar. Probeer de regeling en vraag na drie weken beide groepen of ze werkt.",
            "Two associations request the same hall on Thursday. This is a new rehearsal for this topic: a dance group needs the large hall for movement; a reading group can use the small room, which is available. Try the arrangement and ask both groups after three weeks whether it works.",
            "دو انجمن برای پنجشنبه یک سالن را می‌خواهند. این موقعیت تمرینی جدیدی برای این موضوع است: گروه رقص برای حرکت به سالن بزرگ نیاز دارد؛ گروه مطالعه می‌تواند از اتاق کوچک استفاده کند که خالی است. برنامه را امتحان کنید و پس از سه هفته از هر دو گروه بپرسید آیا مناسب است."),
        loc("Beide groepen willen donderdag de grote zaal. Hoe achterhalen we wat ze echt nodig hebben?", "Both groups want the large hall on Thursday. How can we find out what they actually need?", "هر دو گروه پنجشنبه سالن بزرگ را می‌خواهند. چطور بفهمیم واقعاً به چه نیاز دارند؟"),
        loc("De dansgroep gebruikt de grote zaal, de leesgroep probeert de kleine. Na drie weken vragen we beide groepen of de regeling werkt.", "The dance group uses the large hall; the reading group tries the small room. After three weeks, we'll ask both groups whether the arrangement works.", "گروه رقص از سالن بزرگ استفاده می‌کند؛ گروه مطالعه اتاق کوچک را امتحان می‌کند. پس از سه هفته از هر دو گروه می‌پرسیم آیا برنامه مناسب است."),
        [
            step("ask_needs",
                 loc("Stel voor om eerst de activiteit en de ruimtebehoefte van beide groepen te vragen.", "Propose first asking both groups about their activities and space needs.", "پیشنهاد دهید ابتدا دربارهٔ فعالیت و فضای مورد نیاز هر دو گروه سؤال کنید."),
                 loc("Welke informatie hebben we nodig voor we een zaal toewijzen?", "What information do we need before assigning a room?", "پیش از اختصاص اتاق به چه اطلاعاتی نیاز داریم؟"),
                 loc("Vraag wat beide groepen doen en hoeveel ruimte daarvoor nodig is.", "Ask what both groups do and how much space they need.", "بپرسید هر دو گروه چه کاری انجام می‌دهند و برای آن چقدر فضا لازم دارند."),
                 loc("De dansgroep heeft bewegingsruimte nodig. De leesgroep bespreekt boeken rond een tafel.", "The dance group needs space to move. The reading group discusses books around a table.", "گروه رقص به فضای حرکت نیاز دارد. گروه مطالعه دور میز دربارهٔ کتاب‌ها صحبت می‌کند."),
                 [["beide", "allebei", "elke groep", "iedere groep"], ["activiteit", "activiteiten", "doen"], ["ruimte", "zaal"]],
                 loc("Laten we beide groepen vragen welke activiteit ze doen en hoeveel ruimte ze nodig hebben.", "Let's ask both groups what activity they do and how much space they need.", "بیایید از هر دو گروه بپرسیم چه فعالیتی انجام می‌دهند و چقدر فضا لازم دارند.")),
            step("allocate_rooms",
                 loc("Kies de kleine zaal voor de leesgroep en verklaar waarom.", "Choose the small room for the reading group and explain why.", "اتاق کوچک را برای گروه مطالعه انتخاب کنید و دلیل بیاورید."),
                 loc("De kleine zaal is beschikbaar. Alleen de dansgroep heeft veel bewegingsruimte nodig. Welke zaal kiest u voor de leesgroep en waarom?", "The small room is available. Only the dance group needs lots of movement space. Which room do you choose for the reading group, and why?", "اتاق کوچک خالی است. فقط گروه رقص به فضای زیادی برای حرکت نیاز دارد. کدام اتاق را برای گروه مطالعه انتخاب می‌کنید و چرا؟"),
                 loc("Verbind ‘de kleine zaal’ aan het gesprek rond een tafel.", "Connect ‘de kleine zaal’ to discussion around a table.", "«de kleine zaal» را به گفت‌وگو دور میز ربط دهید."),
                 loc("Dan blijft de grote zaal voor de dansgroep beschikbaar.", "Then the large hall remains available for the dance group.", "پس سالن بزرگ برای گروه رقص در دسترس می‌ماند."),
                 [["leesgroep"], ["tafel", "boeken", "bespreken", "bespreekt", "lezen"]],
                 loc("Ik kies de kleine zaal voor de leesgroep, want daar kunnen de leden rond een tafel boeken bespreken.", "I choose the small room for the reading group because its members can discuss books around a table there.", "اتاق کوچک را برای گروه مطالعه انتخاب می‌کنم، چون اعضا می‌توانند آنجا دور میز دربارهٔ کتاب‌ها صحبت کنند."),
                 [choice("small_room", loc("De kleine zaal", "The small room", "اتاق کوچک"), ["kleine zaal", "kleine ruimte"], True), choice("large_room", loc("De grote zaal", "The large hall", "سالن بزرگ"), ["grote zaal", "grote ruimte"], False)]),
            step("check_experience",
                 loc("Stel een proef voor en vraag na drie weken beide groepen of de regeling werkt.", "Propose a trial and ask both groups after three weeks whether the arrangement works.", "یک دورهٔ آزمایشی پیشنهاد دهید و پس از سه هفته از هر دو گروه بپرسید آیا برنامه مناسب است."),
                 loc("De leesgroep wil eerst ervaren of de kleinere zaal prettig werkt. Wanneer en bij wie vragen we dat na?", "The reading group wants to try the smaller room first. When, and with whom, should we check how it went?", "گروه مطالعه می‌خواهد ابتدا استفاده از اتاق کوچک‌تر را تجربه کند. چه وقت و از چه کسانی نتیجه را بپرسیم؟"),
                 loc("Noem de proef, drie weken en beide groepen.", "Mention the trial, three weeks and both groups.", "به آزمایش، سه هفته و هر دو گروه اشاره کنید."),
                 loc("Goed, we beoordelen de ervaring van allebei.", "Good, we'll review both groups' experiences.", "خوب است، تجربهٔ هر دو گروه را بررسی می‌کنیم."),
                 [["beide groepen", "beide verenigingen", "allebei", "elke groep"], ["werkt", "ervaring", "bevalt", "past", "tevreden"]],
                 loc("We proberen dit. Na drie weken vragen we beide groepen of de regeling werkt.", "We'll try this. After three weeks, we'll ask both groups whether the arrangement works.", "این روش را امتحان می‌کنیم. پس از سه هفته از هر دو گروه می‌پرسیم آیا برنامه مناسب است."),
                 [choice("three_weeks", loc("Na drie weken", "After three weeks", "پس از سه هفته"), ["na drie weken", "na 3 weken", "over drie weken", "over 3 weken"], True), choice("no_review", loc("Zonder overleg", "Without consultation", "بدون مشورت"), ["niet meer vragen", "geen evaluatie", "zonder overleg"], False)]),
        ],
    ),
]


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    path = root / "content" / "conversations" / "pilot.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"schema_version": 1, "review_status": "unreviewed", "conversations": CONVERSATIONS}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(CONVERSATIONS)} conversation rehearsals to {path.relative_to(root)}")


if __name__ == "__main__":
    main()
