"""Original follow-up voice messages for 100 upper-stage communication scenes.

Each row contains a distinct next step and the speaker's explicit rationale.
The source scenes are original course material, not copied textbook extracts.
All NL/EN/FA text is pending qualified language review.
"""

# id | next step (nl~en~fa) | rationale (nl~en~fa)
FOLLOWUPS = r'''
1|Ik laat voortaan iedere deelnemer de uitnodiging bevestigen voordat we de agenda vastleggen.~From now on, I will ask every participant to confirm the invitation before we finalise the agenda.~از این پس از هر شرکت‌کننده می‌خواهم پیش از نهایی کردن دستور جلسه، دریافت دعوت‌نامه را تأیید کند.|Zo merken we een fout adres op voordat iemand de bespreking mist.~That way, we notice an incorrect address before someone misses the discussion.~به این ترتیب پیش از اینکه کسی جلسه را از دست بدهد، متوجه نشانی اشتباه می‌شویم.
2|Ik vraag de personeelsdienst om de afspraken over avondwerk in een apart overzicht te zetten.~I will ask human resources to put the evening-work arrangements in a separate overview.~از منابع انسانی می‌خواهم توافق‌های کار عصر را در خلاصه‌ای جداگانه بنویسد.|Een mondeling antwoord alleen kan later door beide partijen anders worden herinnerd.~A spoken answer alone may later be remembered differently by the two parties.~پاسخ صرفاً شفاهی ممکن است بعداً در خاطر دو طرف متفاوت بماند.
3|Ik stel voor dat iedereen vóór vrijdag aangeeft welke late dienst echt onmogelijk is.~I suggest that everyone indicate before Friday which late shift is genuinely impossible.~پیشنهاد می‌کنم همه پیش از جمعه اعلام کنند کدام شیفت آخر واقعاً برایشان ممکن نیست.|Een eerlijke beurtrol houdt ook rekening met beperkingen die niet iedereen heeft.~A fair rotation also takes account of constraints that not everyone has.~نوبت‌بندی منصفانه محدودیت‌هایی را هم در نظر می‌گیرد که همه ندارند.
4|Ik bel de klant om te controleren of het oude bestand werkelijk vervangen is.~I will call the client to check whether the old file has actually been replaced.~به مشتری زنگ می‌زنم تا بررسی کنم پروندهٔ قدیمی واقعاً جایگزین شده است یا نه.|Een nieuw bestand versturen bewijst nog niet dat de ontvanger de juiste versie gebruikt.~Sending a new file does not prove that the recipient is using the correct version.~فرستادن پروندهٔ تازه ثابت نمی‌کند که گیرنده نسخهٔ درست را استفاده می‌کند.
5|Ik geef de stagiair vijf minuten in het volgende teamoverleg om de proef zelf toe te lichten.~I will give the intern five minutes in the next team meeting to explain the trial personally.~در جلسهٔ بعدی گروه پنج دقیقه به کارآموز فرصت می‌دهم تا خودش آزمایش را توضیح دهد.|De bedenker kan dan zelf vertellen welke kleine verandering verpakkingen heeft bespaard.~The person who devised it can then explain which small change saved packaging.~به این ترتیب صاحب ایده خودش می‌تواند توضیح دهد کدام تغییر کوچک در بسته‌بندی صرفه‌جویی ایجاد کرد.
6|Ik stuur de buurvrouw de gekozen citaten voordat het onderzoeksverslag wordt gedeeld.~I will send the neighbour the selected quotations before the research report is shared.~پیش از انتشار گزارش پژوهش، نقل‌قول‌های انتخاب‌شده را برای همسایه می‌فرستم.|Toestemming voor een gesprek betekent niet vanzelf dat elk persoonlijk detail openbaar mag worden.~Consent to an interview does not automatically mean that every personal detail may be made public.~رضایت برای گفت‌وگو خودبه‌خود به معنای اجازهٔ انتشار تمام جزئیات شخصی نیست.
7|Ik voeg de instellingen van beide toestellen als bijlage bij het proefverslag.~I will attach the settings of both devices to the experiment report.~تنظیم‌های هر دو دستگاه را به گزارش آزمایش پیوست می‌کنم.|Een volgende groep moet de vergelijking met dezelfde instellingen kunnen herhalen.~The next group must be able to repeat the comparison with the same settings.~گروه بعدی باید بتواند مقایسه را با همان تنظیم‌ها تکرار کند.
8|Ik vraag de docent één verbeterde alinea naast de oorspronkelijke alinea te bespreken.~I will ask the lecturer to discuss one revised paragraph alongside the original paragraph.~از مدرس می‌خواهم یک بند بازنویسی‌شده را در کنار بند اصلی بررسی کند.|Dat maakt zichtbaar hoe een bron een bewering kan ondersteunen in plaats van ze alleen langer te maken.~That shows how a source can support a claim rather than merely make it longer.~این کار نشان می‌دهد چگونه منبع می‌تواند از ادعا پشتیبانی کند، نه اینکه فقط آن را طولانی‌تر کند.
9|Ik hang bij beide leesruimtes een overzicht met de stille uren en de uren voor groepswerk.~I will display a schedule of quiet hours and group-work hours at both reading rooms.~کنار هر دو سالن مطالعه، جدول ساعت‌های سکوت و کار گروهی را نصب می‌کنم.|Bezoekers die de bespreking gemist hebben, moeten de nieuwe afspraak ook kunnen begrijpen.~Visitors who missed the discussion must also be able to understand the new arrangement.~بازدیدکنندگانی که در گفت‌وگو نبودند نیز باید بتوانند توافق تازه را بفهمند.
10|Ik mail de spreker mijn samenvatting van het begrip met de vraag of mijn voorbeeld klopt.~I will email the speaker my summary of the concept and ask whether my example is accurate.~خلاصهٔ برداشت خود از مفهوم را برای سخنران ایمیل می‌کنم و می‌پرسم مثالم درست است یا نه.|Een bekend voorbeeld helpt pas als de vergelijking de betekenis niet vervormt.~A familiar example only helps if the comparison does not distort the meaning.~مثال آشنا فقط زمانی کمک می‌کند که مقایسه معنای اصلی را تحریف نکند.
11|Ik stel voor de nieuwe bank eerst met een tijdelijke markering op het plein uit te proberen.~I suggest trying out the new bench location with temporary markings on the square.~پیشنهاد می‌کنم ابتدا جای نیمکت تازه را با علامت‌گذاری موقت در میدان امتحان کنیم.|Dan zien we of er genoeg vrije doorgang overblijft zonder meteen iets vast te bouwen.~Then we can see whether enough clear passage remains without immediately building anything permanent.~آن‌وقت بدون ساخت‌وساز دائمی می‌بینیم آیا مسیر عبور کافی باقی می‌ماند یا نه.
12|Ik vraag de stad om apart te melden hoeveel antwoorden uit de eerder vergeten straat komen.~I will ask the city to report separately how many responses come from the street previously left out.~از شهرداری می‌خواهم جداگانه گزارش دهد چند پاسخ از خیابانی آمده که قبلاً فراموش شده بود.|Een langere termijn helpt alleen als de ontbrekende bewoners werkelijk bereikt worden.~A longer deadline only helps if the missing residents are actually reached.~تمدید مهلت فقط زمانی مفید است که واقعاً به ساکنان جامانده دسترسی پیدا کنیم.
13|Ik verwijder de oproep over de sleutel nu de eigenaar het voorwerp heeft opgehaald.~I will remove the notice about the key now that the owner has collected it.~حالا که صاحب کلید آن را گرفته است، آگهی مربوط به کلید را حذف می‌کنم.|Een oude oproep kan nieuwe reacties uitlokken terwijl er niets meer te zoeken valt.~An old notice may prompt new replies when there is no longer anything to find.~آگهی قدیمی ممکن است پاسخ‌های تازه ایجاد کند، در حالی که دیگر چیزی برای یافتن وجود ندارد.
14|Ik vraag beide verenigingen na drie weken of de kleinere zaal bij hun activiteiten past.~I will ask both associations after three weeks whether the smaller room suits their activities.~پس از سه هفته از هر دو انجمن می‌پرسم آیا سالن کوچک‌تر برای فعالیت‌هایشان مناسب است یا نه.|Een regeling op papier kan eerlijk lijken en toch voor één groep onpraktisch zijn.~An arrangement can look fair on paper yet be impractical for one group.~توافقی ممکن است روی کاغذ منصفانه به نظر برسد، اما برای یک گروه کاربردی نباشد.
15|Ik reserveer twee rustige loketmomenten voor bewoners die hun aanvraag samen willen invullen.~I will reserve two quiet service-desk sessions for residents who want to complete their application with assistance.~دو زمان خلوت در پیشخوان برای ساکنانی رزرو می‌کنم که می‌خواهند درخواستشان را با کمک تکمیل کنند.|Persoonlijke begeleiding vraagt tijd en mag geen haastige bijzaak aan een druk loket worden.~Personal assistance takes time and should not become a rushed extra at a busy desk.~کمک فردی زمان می‌خواهد و نباید در پیشخوان شلوغ به کاری عجولانه و فرعی تبدیل شود.
16|Ik vraag de technicus om na de dakherstelling ook de vochtplek binnen opnieuw te bekijken.~I will ask the technician to inspect the damp patch inside again after the roof repair.~از تعمیرکار می‌خواهم پس از تعمیر سقف، لکهٔ رطوبت داخل را هم دوباره بررسی کند.|Een gedicht lek betekent niet dat alle achtergebleven schade al zichtbaar is.~A sealed leak does not mean that all remaining damage is already visible.~بسته شدن نشتی به معنای آشکار شدن تمام خسارت‌های باقی‌مانده نیست.
17|Ik stel een proefmaand met verplaatsbare plantenbakken voor voordat de binnenplaats een vaste tuin wordt.~I suggest a trial month with movable planters before turning the courtyard into a permanent garden.~پیشنهاد می‌کنم پیش از تبدیل حیاط به باغ دائمی، یک ماه گلدان‌های قابل‌جابه‌جایی را امتحان کنیم.|Bewoners kunnen zo ervaren hoeveel ruimte en rust het nieuwe gebruik oplevert.~Residents can then experience how much space and quiet the new use provides.~به این ترتیب ساکنان می‌توانند تجربه کنند استفادهٔ تازه چقدر فضا و آرامش ایجاد می‌کند.
18|Ik vraag om een nieuwe afrekening waarop de gecorrigeerde meterstand duidelijk naast de oude staat.~I will request a new bill clearly showing the corrected meter reading alongside the old one.~صورت‌حساب تازه‌ای می‌خواهم که عدد اصلاح‌شدهٔ کنتور را روشن در کنار عدد قبلی نشان دهد.|Met alleen een lager totaalbedrag kan ik de gemaakte correctie niet controleren.~A lower total alone does not let me check which correction was made.~فقط با مبلغ کل کمتر نمی‌توانم بررسی کنم چه اصلاحی انجام شده است.
19|Ik nodig de bouwfirma uit om de schaduw van het aangepaste ontwerp op dezelfde uren te tonen.~I will invite the construction company to show the shadow from the revised design at the same times of day.~از شرکت ساختمانی دعوت می‌کنم سایهٔ طرح اصلاح‌شده را در همان ساعت‌های روز نشان دهد.|Twee beelden zijn moeilijk vergelijkbaar wanneer het ene in de ochtend en het andere in de avond is gemaakt.~Two images are difficult to compare when one shows morning and the other evening.~مقایسهٔ دو تصویر دشوار است وقتی یکی صبح و دیگری عصر را نشان می‌دهد.
20|Ik schrijf de twee afgesproken wasmomenten op en vraag de huisgenoten wanneer we die afspraak herbekijken.~I will write down the two agreed laundry times and ask the housemates when we will review the arrangement.~دو زمان توافق‌شده برای لباس‌شویی را می‌نویسم و از هم‌خانه‌ها می‌پرسم چه زمانی توافق را بازبینی کنیم.|Een werkrooster kan veranderen, waardoor een redelijk compromis later toch niet meer werkt.~Work schedules can change, so a reasonable compromise may stop working later.~برنامهٔ کاری ممکن است عوض شود و سازشی معقول بعداً دیگر کار نکند.
21|Ik plaats de datum van de oorspronkelijke foto zichtbaar boven de rechtzetting.~I will put the date of the original photograph clearly above the correction.~تاریخ عکس اصلی را به‌وضوح بالای اصلاحیه قرار می‌دهم.|Lezers die alleen de eerste regels zien, moeten meteen begrijpen dat het geen nieuwe overstroming is.~Readers who only see the first lines should immediately understand that this is not a new flood.~خوانندگانی که فقط سطرهای اول را می‌بینند باید فوراً بفهمند این سیل تازه‌ای نیست.
22|Ik vraag de redactie om zowel het aantal deelnemers als de onzekerheid in de nieuwe kop te verwerken.~I will ask the editors to include both the number of participants and the uncertainty in the new headline.~از تحریریه می‌خواهم هم تعداد شرکت‌کنندگان و هم عدم قطعیت را در تیتر تازه بگنجاند.|Een minder uitbundige kop kan nog altijd te stellig zijn over een kleine studie.~A less enthusiastic headline may still sound too certain about a small study.~تیتر کم‌هیجان‌تر نیز ممکن است دربارهٔ پژوهش کوچک همچنان بیش‌ازحد قطعی باشد.
23|Ik speel het volledige antwoord van de marktkramer af voordat we het korte citaat opnieuw kiezen.~I will play the trader's complete answer before we select the short quotation again.~پیش از انتخاب دوبارهٔ نقل‌قول کوتاه، پاسخ کامل فروشنده را پخش می‌کنم.|De woorden alleen laten niet horen dat hij op dat moment een grap maakte.~The words alone do not reveal that he was joking at that moment.~کلمات به‌تنهایی نشان نمی‌دهند که او در آن لحظه شوخی می‌کرد.
24|Ik zet bij de rugzaktip bovenaan welke vergoeding ik voor de bespreking ontving.~I will state at the top of the backpack review what payment I received for it.~بالای مطلب کوله‌پشتی می‌نویسم برای این بررسی چه حق‌الزحمه‌ای گرفته‌ام.|Een lezer hoort dat belang te kennen voordat hij de aanbeveling beoordeelt.~A reader should know about that interest before judging the recommendation.~خواننده باید پیش از ارزیابی توصیه از این منفعت آگاه باشد.
25|Ik maak voor mijn gezin een kort stappenkaartje met het officiële contactkanaal van de bank.~I will make a short step-by-step card for my family with the bank's official contact channel.~برای خانواده‌ام کارت راهنمای کوتاهی با راه تماس رسمی بانک تهیه می‌کنم.|Onder tijdsdruk is het verleidelijk om het telefoonnummer uit een verdacht bericht zelf te gebruiken.~Under time pressure, it is tempting to use the number provided in a suspicious message itself.~زیر فشار زمان، استفاده از شماره‌ای که در خود پیام مشکوک آمده وسوسه‌کننده است.
26|Ik verdeel de herfstcontrole van de afvoerroosters over twee bewoners en noteer wanneer ze klaar is.~I will divide the autumn drain checks between two residents and record when they are complete.~بررسی پاییزی دریچه‌های فاضلاب را بین دو ساکن تقسیم می‌کنم و زمان پایان آن را ثبت می‌کنم.|Een algemene belofte om beter op te letten maakt nog niemand verantwoordelijk voor de uitvoering.~A general promise to pay more attention does not make anyone responsible for doing the work.~قول کلی برای دقت بیشتر، کسی را مسئول اجرای کار نمی‌کند.
27|Ik vraag de school om eerst één proefbak te plaatsen en de schaduw op het plein te volgen.~I will ask the school to install one trial planter first and monitor the shade on the playground.~از مدرسه می‌خواهم ابتدا یک گلدان آزمایشی بگذارد و سایهٔ حیاط را بررسی کند.|Een geschikte draaglast alleen vertelt nog niet of de gekozen plek merkbaar verkoeling brengt.~A suitable load alone does not tell us whether the chosen location noticeably cools the area.~تحمل وزن مناسب به‌تنهایی نشان نمی‌دهد که محل انتخاب‌شده واقعاً فضا را خنک می‌کند.
28|Ik hang bij de kassa een foto van een aanvaardbare retourfles naast een beschadigd voorbeeld.~I will display a photograph of an acceptable return bottle beside a damaged example at the checkout.~کنار صندوق، عکس بطری قابل‌قبول برای بازگشت را کنار نمونهٔ آسیب‌دیده نصب می‌کنم.|Klanten begrijpen de voorwaarde sneller wanneer ze het verschil kunnen zien.~Customers understand the condition faster when they can see the difference.~مشتریان وقتی تفاوت را می‌بینند، شرط را سریع‌تر می‌فهمند.
29|Ik laat de vereniging de nieuwe raming goedkeuren voordat de panelen worden besteld.~I will ask the association to approve the revised estimate before the panels are ordered.~از انجمن می‌خواهم پیش از سفارش پنل‌ها، برآورد اصلاح‌شده را تأیید کند.|Een positief project blijft een andere investering wanneer de terugverdientijd langer wordt.~A viable project still becomes a different investment when the payback period grows longer.~طرحی سودمند نیز وقتی دورهٔ بازگشت سرمایه طولانی‌تر شود، سرمایه‌گذاری متفاوتی خواهد بود.
30|Ik vraag de milieudienst om in de bewonersbrief metingen en vermoedens afzonderlijk te benoemen.~I will ask the environmental service to distinguish measurements from suspicions in the residents' letter.~از ادارهٔ محیط زیست می‌خواهم در نامهٔ ساکنان، اندازه‌گیری‌ها و حدس‌ها را جدا بیان کند.|Een bedrijf beschuldigen op basis van een eerste indruk kan het onderzoek en het vertrouwen schaden.~Blaming a company on a first impression can harm both the investigation and trust.~متهم کردن شرکت بر پایهٔ برداشت اولیه می‌تواند به بررسی و اعتماد آسیب بزند.
31|Ik test de nieuwe vertaling bij iemand die het oorspronkelijke verhaal niet kent.~I will test the new translation with someone who does not know the original story.~ترجمهٔ تازه را با کسی امتحان می‌کنم که داستان اصلی را نمی‌شناسد.|Een vriend die de grap al kent, vult ontbrekende betekenis misschien onbewust aan.~A friend who already knows the joke may unconsciously fill in missing meaning.~دوستی که از قبل شوخی را می‌شناسد ممکن است ناخودآگاه معنای جاافتاده را تکمیل کند.
32|Ik vraag de ontvangst om bij gelijke namen ook het reserveringsnummer te controleren.~I will ask reception to check the booking number whenever names match.~از پذیرش می‌خواهم در صورت یکسان بودن نام‌ها، شمارهٔ رزرو را هم بررسی کند.|Twee bezoekers met dezelfde naam hebben niet noodzakelijk dezelfde reservering.~Two visitors with the same name do not necessarily have the same booking.~دو بازدیدکننده با نام یکسان لزوماً رزرو یکسانی ندارند.
33|Ik laat na elke demonstratie het gereedschap op een vaste plek met een eenvoudige lijst controleren.~I will arrange for the tools to be checked against a simple list in a fixed place after every demonstration.~ترتیب می‌دهم پس از هر نمایش، ابزارها در محل مشخصی با فهرستی ساده بررسی شوند.|Een duidelijke opruimroutine voorkomt dat een zoekgeraakt voorwerp meteen als diefstal wordt uitgelegd.~A clear tidying routine prevents a missing object from immediately being interpreted as theft.~روال روشن جمع‌کردن مانع می‌شود گم شدن وسیله فوراً دزدی تلقی شود.
34|Ik vraag de nieuwe makers hoe zij de papieren oproep hebben gevonden.~I will ask the new artists how they came across the printed invitation.~از هنرمندان تازه می‌پرسم چگونه با فراخوان کاغذی آشنا شده‌اند.|Dan weten we welke verspreidingskanalen werkelijk andere deelnemers bereiken.~Then we know which distribution channels actually reach different participants.~آن‌وقت می‌فهمیم کدام راه‌های توزیع واقعاً به شرکت‌کنندگان متفاوت دسترسی پیدا می‌کنند.
35|Ik vraag het gezin om bij de lampjes kort uit te leggen wat het licht voor hen betekent.~I will ask the family to briefly explain what the light means to them when using the lamps.~از خانواده می‌خواهم کنار چراغ‌ها کوتاه توضیح دهد نور برایشان چه معنایی دارد.|Een veilige vervanging bewaart de traditie beter wanneer ook de betekenis zichtbaar blijft.~A safe substitute preserves the tradition better when its meaning also remains visible.~جایگزین ایمن وقتی معنای رسم نیز روشن بماند، بهتر آن را حفظ می‌کند.
36|Ik vraag aan het gevondenvoorwerpenloket hoe ik een volgende vondst het best kan afgeven.~I will ask the lost-property desk how best to hand in anything I find in future.~از بخش اشیای گمشده می‌پرسم دفعهٔ بعد چگونه بهتر است وسیلهٔ پیداشده را تحویل دهم.|Wie de procedure vooraf kent, hoeft op een onverwacht moment minder te improviseren.~Someone who knows the procedure in advance has less need to improvise unexpectedly.~کسی که روال را از قبل بداند، در موقعیت غیرمنتظره کمتر ناچار به تصمیم‌گیری بداهه است.
37|Ik laat het team vóór de volgende indiening samen de auteurslijst nakijken.~I will ask the team to check the author list together before the next submission.~از گروه می‌خواهم پیش از تحویل بعدی، فهرست نویسندگان را با هم بررسی کند.|Achteraf erkenning herstellen is lastiger dan bijdragen tijdens het werk zichtbaar maken.~Restoring recognition afterwards is harder than making contributions visible during the work.~جبران دیده‌نشدن سهم افراد پس از کار دشوارتر از روشن کردن مشارکت‌ها در حین کار است.
38|Ik vraag de fietser of hij wil dat ik blijf wachten tot zijn familielid aankomt.~I will ask the cyclist whether he wants me to wait until his relative arrives.~از دوچرخه‌سوار می‌پرسم می‌خواهد تا رسیدن عضو خانواده‌اش منتظر بمانم یا نه.|Een eerste toestemming om te bellen is nog geen toestemming voor elke volgende vorm van hulp.~Initial permission to call is not permission for every subsequent form of assistance.~رضایت اولیه برای تماس، اجازهٔ هر نوع کمک بعدی نیست.
39|Ik vervang de openbare telefoonlijst door een bericht met alleen de naam van de contactpersoon.~I will replace the public telephone list with a notice showing only the contact person's name.~فهرست عمومی شماره‌ها را با اعلانی که فقط نام فرد پاسخ‌گو را دارد جایگزین می‌کنم.|Leden moeten hulp kunnen vinden zonder dat de telefoonnummers van iedereen zichtbaar zijn.~Members should be able to find help without everyone's phone numbers being visible.~اعضا باید بتوانند کمک بگیرند، بدون اینکه شمارهٔ تلفن همه آشکار باشد.
40|Ik bevestig schriftelijk dat de bestelling volgens dezelfde voorwaarden als andere bestellingen wordt beoordeeld.~I will confirm in writing that the order will be assessed under the same conditions as other orders.~کتبی تأیید می‌کنم که سفارش با همان شرایط سفارش‌های دیگر ارزیابی می‌شود.|Een beleefde weigering van het geschenk laat anders nog ruimte voor verwachtingen over een gunst.~A polite refusal of the gift may otherwise still leave room for expectations of a favour.~رد مؤدبانهٔ هدیه در غیر این صورت ممکن است همچنان انتظار لطف ایجاد کند.
41|Ik schrijf mijn resterende vragen in gewone woorden op en bespreek ze opnieuw met de apotheker.~I will write down my remaining questions in plain language and discuss them again with the pharmacist.~پرسش‌های باقی‌مانده را با واژه‌های ساده می‌نویسم و دوباره با داروساز مطرح می‌کنم.|Een medische term nazeggen betekent niet dat ik de instructie werkelijk begrepen heb.~Repeating a medical term does not mean I have actually understood the instruction.~تکرار اصطلاح پزشکی به معنای فهم واقعی دستور نیست.
42|Ik vraag de leidinggevende om de korte pauzes ook in de vergaderagenda zichtbaar te maken.~I will ask the manager to show the short breaks in the meeting schedule too.~از مدیر می‌خواهم استراحت‌های کوتاه را در برنامهٔ جلسه‌ها هم مشخص کند.|Een pauze verdwijnt gemakkelijk wanneer de volgende vergadering automatisch aansluit.~A break can easily disappear when the next meeting automatically follows.~وقتی جلسهٔ بعدی خودکار پشت جلسهٔ قبلی بیاید، زمان استراحت به‌آسانی حذف می‌شود.
43|Ik wandel met een medewerker vanaf de hoofdingang tot aan de helling om de pijlen te testen.~I will walk with a staff member from the main entrance to the ramp to test the signs.~با کارمند از ورودی اصلی تا سطح شیب‌دار می‌روم تا تابلوها را امتحان کنیم.|Wie de route al kent, merkt ontbrekende aanwijzingen niet altijd op.~Someone who already knows the route does not always notice missing directions.~کسی که مسیر را از قبل می‌شناسد همیشه متوجه راهنمایی‌های ناقص نمی‌شود.
44|Ik vraag de lokale dienst wat er gebeurt als het vaste opvangmoment onverwacht wegvalt.~I will ask the local service what happens if the regular respite session is unexpectedly cancelled.~از خدمات محلی می‌پرسم اگر نوبت ثابت مراقبت ناگهان لغو شود چه می‌شود.|Een regeling geeft minder rust wanneer er geen aanspreekpunt is voor uitzonderingen.~An arrangement provides less peace of mind when there is no contact person for exceptions.~توافقی که برای وضعیت استثنایی فرد پاسخ‌گو ندارد، آرامش کمتری ایجاد می‌کند.
45|Ik stuur nieuwe wandelaars vooraf een korte beschrijving van afstand, tempo en pauzes.~I will send new walkers a short description of distance, pace and breaks in advance.~از قبل توضیح کوتاهی دربارهٔ مسافت، سرعت و استراحت‌ها برای تازه‌واردان پیاده‌روی می‌فرستم.|Onzekerheid over praktische details kan groter zijn dan de wandeling zelf.~Uncertainty about practical details can feel bigger than the walk itself.~ابهام دربارهٔ جزئیات عملی ممکن است از خود پیاده‌روی بزرگ‌تر به نظر برسد.
46|Ik vraag aan de balie welke velden verplicht zijn en welke ik later met de zorgverlener kan bespreken.~I will ask at reception which fields are required and which I can discuss later with the care provider.~در پذیرش می‌پرسم کدام بخش‌ها الزامی است و کدام را می‌توانم بعداً با ارائه‌دهندهٔ مراقبت مطرح کنم.|Ik wil de informatie juist geven zonder onder tijdsdruk iets verkeerd te begrijpen.~I want to give accurate information without misunderstanding something under time pressure.~می‌خواهم اطلاعات درست بدهم، بدون اینکه زیر فشار زمان چیزی را اشتباه بفهمم.
47|Ik laat het jongerenpanel één boodschap navertellen zonder naar de nieuwe affiche te kijken.~I will ask the youth panel to explain one message without looking at the new poster.~از گروه جوانان می‌خواهم یک پیام را بدون نگاه کردن به پوستر تازه بازگو کند.|Een tekst prettig vinden is niet hetzelfde als de kern ervan kunnen uitleggen.~Liking a text is not the same as being able to explain its main point.~پسندیدن متن با توان توضیح نکتهٔ اصلی آن یکسان نیست.
48|Ik vraag de praktijk een vrijgekomen afspraak per sms te melden met een duidelijk antwoordmoment.~I will ask the practice to notify me of an available appointment by text with a clear reply deadline.~از مطب می‌خواهم وقت آزادشده را با پیامک و مهلت پاسخ روشن اطلاع دهد.|Tijdens het werk kan ik niet altijd bellen, maar een kort bericht kan ik later gericht beantwoorden.~I cannot always call at work, but I can respond deliberately to a short message later.~سر کار همیشه نمی‌توانم زنگ بزنم، اما بعداً می‌توانم مشخص به پیام کوتاه پاسخ دهم.
49|Ik vraag de lesgever bij elke oefening ook een lichtere keuzemogelijkheid te tonen.~I will ask the instructor to demonstrate an easier alternative for each exercise too.~از مربی می‌خواهم برای هر تمرین، گزینهٔ سبک‌تر را هم نشان دهد.|Een deelnemer kan pas kiezen als het alternatief duidelijk uitgelegd is.~A participant can only choose when the alternative has been explained clearly.~شرکت‌کننده فقط وقتی می‌تواند انتخاب کند که گزینهٔ جایگزین روشن توضیح داده شده باشد.
50|Ik stel voor dat het team één afzonderlijk kanaal afspreekt voor echt dringende avondvragen.~I suggest that the team agree on one separate channel for genuinely urgent evening questions.~پیشنهاد می‌کنم گروه یک راه ارتباطی جدا برای پرسش‌های واقعاً فوری عصر تعیین کند.|Anders krijgt ieder gewoon bericht opnieuw het gewicht van een noodgeval.~Otherwise, every ordinary message once again takes on the weight of an emergency.~در غیر این صورت هر پیام عادی دوباره اهمیت وضعیت اضطراری پیدا می‌کند.
51|Ik vraag de klantendienst mijn einddatum en het laatste te betalen bedrag in één bericht te bevestigen.~I will ask customer service to confirm my end date and final amount due in one message.~از خدمات مشتری می‌خواهم تاریخ پایان و آخرین مبلغ پرداختی را در یک پیام تأیید کند.|Een bevestigde opzegging zegt zonder die details nog niet wanneer alle betalingen stoppen.~A cancellation confirmation without those details does not yet say when all payments stop.~تأیید لغو بدون این جزئیات هنوز نشان نمی‌دهد همهٔ پرداخت‌ها چه زمانی پایان می‌یابند.
52|Ik vraag de winkelmedewerker het juiste prijsetiket bij het juiste model te hangen.~I will ask the shop assistant to put the correct price label beside the correct model.~از فروشنده می‌خواهم برچسب قیمت درست را کنار مدل درست بگذارد.|Een korting voor mij lost de verwarring voor de volgende klant niet op.~A discount for me does not solve the confusion for the next customer.~تخفیف برای من سردرگمی مشتری بعدی را حل نمی‌کند.
53|Ik leg de twee begrotingen naast elkaar en vermeld welke versiering kan vervallen.~I will compare the two budgets side by side and state which decorations can be dropped.~دو بودجه را کنار هم می‌گذارم و مشخص می‌کنم کدام تزئینات را می‌توان حذف کرد.|Een reserve blijft alleen echt beschikbaar als we vooraf weten waarop we kunnen besparen.~A reserve only remains genuinely available if we know beforehand where we can save.~ذخیره فقط وقتی واقعاً باقی می‌ماند که از قبل بدانیم کجا می‌توان صرفه‌جویی کرد.
54|Ik stuur het betalingsbewijs opnieuw met mijn inschrijvingsnummer in het onderwerp van de mail.~I will resend the payment receipt with my enrolment number in the email subject.~رسید پرداخت را دوباره با شمارهٔ ثبت‌نام در عنوان ایمیل می‌فرستم.|De administratie moet de ontvangen betaling zonder zoekwerk aan de juiste cursist kunnen koppelen.~The administration should be able to link the payment to the correct learner without a lengthy search.~بخش اداری باید بتواند بدون جست‌وجوی طولانی پرداخت را به زبان‌آموز درست وصل کند.
55|Ik vraag de medewerker om een lijst van de nog ontbrekende bewijsstukken met de uiterste datum.~I will ask the staff member for a list of the documents still missing and the final deadline.~از کارمند فهرست مدارک هنوز ناقص و آخرین مهلت را می‌خواهم.|Nog een verkeerde of onvolledige aanvulling kan de resterende tijd onnodig verbruiken.~Another incorrect or incomplete addition may waste the remaining time.~تکمیل اشتباه یا ناقص دیگر ممکن است وقت باقی‌مانده را بیهوده مصرف کند.
56|Ik vraag beide herstellers welke onderdelen en werkuren precies in hun offerte zitten.~I will ask both repairers exactly which parts and labour hours their quotations include.~از هر دو تعمیرکار می‌پرسم دقیقاً چه قطعه‌ها و ساعت‌های کاری در پیشنهاد قیمتشان هست.|Twee eindbedragen zijn geen eerlijke vergelijking wanneer de inhoud verschilt.~Two final prices are not a fair comparison when the contents differ.~مقایسهٔ دو مبلغ نهایی وقتی محتوا متفاوت است منصفانه نیست.
57|Ik vraag aan het loket welke formule past bij twee vaste spitsritten per week.~I will ask at the ticket desk which fare option suits two regular peak-time journeys a week.~از باجه می‌پرسم کدام گزینه برای دو سفر ثابت هفتگی در ساعت شلوغ مناسب است.|De goedkoopste losse rit is niet noodzakelijk de voordeligste keuze voor mijn hele week.~The cheapest individual journey is not necessarily the best-value choice for my whole week.~ارزان‌ترین سفر تکی لزوماً به‌صرفه‌ترین انتخاب برای کل هفتهٔ من نیست.
58|Ik vraag de eerste dienst vooraf te controleren of de tweede dienst mijn vraag echt behandelt.~I will ask the first service to check in advance that the second service actually handles my question.~از ادارهٔ اول می‌خواهم از قبل بررسی کند ادارهٔ دوم واقعاً به پرسش من رسیدگی می‌کند.|Nog een doorverwijzing zonder controle zou dezelfde wachttijd opnieuw veroorzaken.~Another unchecked referral would create the same waiting time again.~ارجاع دیگر بدون بررسی همان زمان انتظار را دوباره ایجاد می‌کند.
59|Ik stel voor bij elke uitleen de toestand van de boormachine kort samen te bekijken.~I suggest checking the drill's condition together briefly whenever it is borrowed.~پیشنهاد می‌کنم هر بار هنگام امانت دادن، وضعیت دریل را کوتاه با هم بررسی کنیم.|Dan is achteraf duidelijker of schade nieuw is of al vóór het gebruik bestond.~Then it is clearer afterwards whether damage is new or existed before use.~آن‌وقت بعداً روشن‌تر است که آسیب تازه است یا پیش از استفاده وجود داشته است.
60|Ik vraag beide organisaties één concreet resultaat en de onzekerheid daarbij te beschrijven.~I will ask both organisations to describe one concrete result and the uncertainty around it.~از هر دو سازمان می‌خواهم یک نتیجهٔ مشخص و عدم قطعیت مربوط به آن را توضیح دهند.|Alleen kosten vergelijken vertelt weinig over wat een schenking werkelijk verandert.~Comparing costs alone says little about what a donation actually changes.~مقایسهٔ هزینه‌ها به‌تنهایی دربارهٔ تغییری که کمک واقعاً ایجاد می‌کند اطلاعات کمی می‌دهد.
61|Ik controleer na de volgende app-update opnieuw welke machtigingen zijn ingeschakeld.~I will check which permissions are enabled again after the next app update.~پس از به‌روزرسانی بعدی برنامه دوباره بررسی می‌کنم کدام مجوزها فعال است.|Een eerder beperkte toegang kan veranderen wanneer functies worden toegevoegd.~Previously limited access can change when features are added.~دسترسی محدود قبلی ممکن است با اضافه شدن قابلیت‌ها تغییر کند.
62|Ik laat ook enkele afgewezen brieven zonder naam opnieuw door een medewerker beoordelen.~I will have a staff member reassess some rejected applications without names attached.~چند درخواست ردشده را هم بدون نام به کارمند می‌دهم تا دوباره ارزیابی کند.|Alleen de gekozen kandidaten bekijken laat mogelijke gemiste talenten buiten beeld.~Looking only at selected candidates leaves potentially overlooked talent unseen.~بررسی فقط پذیرفته‌شدگان، استعدادهای احتمالاً نادیده‌گرفته‌شده را پنهان نگه می‌دارد.
63|Ik vermeld in mijn terugmelding zowel de afgesloten brug als de gevolgde omleiding.~I will include both the closed bridge and the diversion I followed in my report.~در گزارش خود هم پل بسته و هم مسیر جایگزینی را که رفتم ذکر می‌کنم.|De kaartendienst heeft meer aan een bruikbaar alternatief dan aan alleen de melding dat iets fout is.~The map service benefits more from a usable alternative than merely being told something is wrong.~برای خدمات نقشه، جایگزین قابل‌استفاده مفیدتر از صرفاً اعلام اشتباه است.
64|Ik maak met de beheerder een lijst van wie nog toegang nodig heeft na de vrijwilligerswissel.~I will make a list with the administrator of who still needs access after the volunteer changeover.~با مسئول فهرست کسانی را تهیه می‌کنم که پس از تغییر داوطلبان هنوز به دسترسی نیاز دارند.|Persoonlijke accounts beschermen weinig als oude toegangsrechten onbeperkt blijven bestaan.~Individual accounts offer little protection if old access rights remain indefinitely.~حساب‌های فردی وقتی دسترسی‌های قدیمی نامحدود باقی بماند، محافظت کمی ایجاد می‌کنند.
65|Ik vraag de organisatie om tijdens een storing te tonen of antwoorden al opgeslagen zijn.~I will ask the organisation to show during an outage whether answers have already been saved.~از سازمان می‌خواهم هنگام اختلال نشان دهد آیا پاسخ‌ها ذخیره شده‌اند یا نه.|Zonder die informatie vullen mensen misschien hetzelfde formulier opnieuw in.~Without that information, people may fill in the same form again.~بدون این اطلاعات، افراد ممکن است همان فرم را دوباره تکمیل کنند.
66|Ik laat de herstelde website opnieuw testen door iemand die niet bij de eerste test betrokken was.~I will have the repaired website retested by someone who was not involved in the first test.~وب‌سایت اصلاح‌شده را برای آزمون دوباره به کسی می‌دهم که در آزمون اول نبوده است.|Een bekende route kan problemen verbergen die een nieuwe bezoeker wel tegenkomt.~A familiar route can hide problems that a new visitor encounters.~مسیر آشنا ممکن است مشکلاتی را پنهان کند که بازدیدکنندهٔ تازه با آن‌ها روبه‌رو می‌شود.
67|Ik noteer wekelijks één handmatige meting naast de waarde van de vochtsensor.~I will record one manual reading alongside the moisture sensor value each week.~هر هفته یک اندازه‌گیری دستی را کنار مقدار حسگر رطوبت ثبت می‌کنم.|Een toestel dat vandaag goed afgesteld is, kan later opnieuw afwijken.~A device correctly adjusted today may drift again later.~دستگاهی که امروز درست تنظیم شده است ممکن است بعداً دوباره خطا پیدا کند.
68|Ik voeg aan de documentatie een klein voorbeeld toe dat een nieuwe vrijwilliger zelf kan uitvoeren.~I will add a small example to the documentation that a new volunteer can run independently.~نمونهٔ کوچکی به مستندات اضافه می‌کنم که داوطلب تازه بتواند خودش اجرا کند.|Uitleg is pas bruikbaar wanneer iemand zonder voorkennis de eerste stap kan zetten.~Instructions become useful when someone without prior knowledge can take the first step.~توضیح وقتی کاربردی است که فرد بدون دانش قبلی بتواند نخستین قدم را بردارد.
69|Ik vraag het team na de proefweek welke onderbrekingen echt niet konden wachten.~I will ask the team after the trial week which interruptions genuinely could not wait.~پس از هفتهٔ آزمایشی از گروه می‌پرسم کدام وقفه‌ها واقعاً نمی‌توانستند منتظر بمانند.|Een te ruime uitzondering kan de afgesproken concentratieperiode volledig uithollen.~An overly broad exception can completely undermine the agreed focus period.~استثنای بیش‌ازحد گسترده می‌تواند زمان تمرکز توافق‌شده را کاملاً بی‌اثر کند.
70|Ik vraag een familielid een foto terug te vinden met alleen de nieuwe bestandsnaam.~I will ask a relative to find a photograph using only its new file name.~از یکی از اعضای خانواده می‌خواهم فقط با نام تازهٔ پرونده یک عکس را پیدا کند.|Een naam die voor mij duidelijk is, hoeft voor een ander nog geen bruikbare aanwijzing te zijn.~A name that is clear to me may not yet be a useful clue to someone else.~نامی که برای من روشن است لزوماً برای دیگری راهنمای مفیدی نیست.
71|Ik fotografeer de halte vanuit beide looprichtingen voordat ik de vervoersmaatschappij schrijf.~I will photograph the stop from both walking directions before writing to the transport company.~پیش از نوشتن به شرکت حمل‌ونقل، از هر دو جهت پیاده‌روی از ایستگاه عکس می‌گیرم.|Eén duidelijk beeld kan verbergen dat hetzelfde bord vanuit de andere richting nauwelijks zichtbaar is.~One clear image can conceal that the same sign is barely visible from the other direction.~یک تصویر واضح ممکن است پنهان کند که همان تابلو از جهت دیگر به‌سختی دیده می‌شود.
72|Ik vraag de informatiebalie ook waar de vervangbus precies vertrekt.~I will also ask the information desk exactly where the replacement bus departs.~از اطلاعات می‌پرسم اتوبوس جایگزین دقیقاً از کجا حرکت می‌کند.|Een korte wachttijd helpt niet als we ondertussen bij de verkeerde halte staan.~A short waiting time does not help if we are standing at the wrong stop.~انتظار کوتاه وقتی در ایستگاه اشتباه باشیم کمکی نمی‌کند.
73|Ik stel voor na de verplaatsing opnieuw op dezelfde uren fietsen te tellen.~I suggest counting bicycles at the same times again after moving the racks.~پیشنهاد می‌کنم پس از جابه‌جایی پایه‌ها، دوچرخه‌ها را دوباره در همان ساعت‌ها بشماریم.|Anders weten we niet of de betere bezetting door de nieuwe plek of een rustigere dag komt.~Otherwise, we cannot tell whether the improved occupancy comes from the new location or a quieter day.~در غیر این صورت نمی‌فهمیم استفادهٔ بهتر ناشی از محل تازه است یا روز خلوت‌تر.
74|Ik vraag de leverancier de laadzone op de routebeschrijving voor chauffeurs te vermelden.~I will ask the supplier to include the loading bay in the route instructions for drivers.~از تأمین‌کننده می‌خواهم محل بارگیری را در راهنمای مسیر رانندگان ذکر کند.|Dezelfde hinder kan terugkomen wanneer morgen een andere chauffeur levert.~The same obstruction may recur when a different driver delivers tomorrow.~اگر فردا رانندهٔ دیگری تحویل دهد، همان مزاحمت ممکن است تکرار شود.
75|Ik nodig de handelaar uit om mee te bepalen welke uren we tijdens de volgende speelstraat meten.~I will invite the shopkeeper to help decide which hours we measure during the next play-street event.~از مغازه‌دار دعوت می‌کنم در تعیین ساعت‌هایی که هنگام خیابان بازی بعدی بررسی می‌کنیم مشارکت کند.|Een evaluatie krijgt meer vertrouwen wanneer ook bezorgde betrokkenen invloed op de vragen hebben.~An evaluation earns more trust when concerned stakeholders also influence the questions.~ارزیابی وقتی اعتماد بیشتری می‌گیرد که افراد نگران نیز بر پرسش‌ها اثر داشته باشند.
76|Ik laat een medestudent de aangevulde bronvermelding opzoeken zonder mijn hulp.~I will ask a fellow student to look up the completed reference without my help.~از هم‌کلاسی می‌خواهم ارجاع تکمیل‌شده را بدون کمک من پیدا کند.|Dat ik de bron zelf terugvind, bewijst nog niet dat de verwijzing voor anderen volledig is.~My ability to find the source does not prove that the reference is complete for others.~اینکه خودم منبع را پیدا می‌کنم ثابت نمی‌کند ارجاع برای دیگران کامل است.
77|Ik stuur de docent vooraf welke twee stukken van de afstandsles ik door het slechte geluid miste.~I will tell the lecturer beforehand which two parts of the remote class I missed because of poor sound.~از قبل به مدرس می‌گویم کدام دو بخش کلاس از راه دور را به‌دلیل صدای نامناسب از دست دادم.|Een korte inhaalsessie is nuttiger wanneer ze op concrete hiaten gericht is.~A short catch-up session is more useful when it focuses on specific gaps.~جلسهٔ جبرانی کوتاه وقتی بر کمبودهای مشخص تمرکز کند مفیدتر است.
78|Ik vraag de leerlingen bij elke plantennaam ook te noteren wie die naam gebruikt.~I will ask pupils to note who uses each plant name as well.~از دانش‌آموزان می‌خواهم برای هر نام گیاه، استفاده‌کنندگان آن نام را هم ثبت کنند.|Twee woorden kunnen naar dezelfde plant verwijzen en toch in verschillende situaties passen.~Two words may refer to the same plant yet fit different situations.~دو واژه ممکن است به یک گیاه اشاره کنند، اما مناسب موقعیت‌های متفاوت باشند.
79|Ik vraag de werkgroep een kleine proef met regenwateropvang te kiezen die meerdere percelen helpt.~I will ask the working group to select a small rainwater-storage trial that benefits several plots.~از کارگروه می‌خواهم آزمایش کوچکی برای ذخیرهٔ باران انتخاب کند که به چند قطعه زمین کمک کند.|Water houdt niet bij een perceelgrens op, dus afzonderlijke plannen kunnen elkaar tegenwerken.~Water does not stop at plot boundaries, so separate plans may work against each other.~آب در مرز زمین متوقف نمی‌شود؛ بنابراین برنامه‌های جدا ممکن است با هم ناسازگار شوند.
80|Ik laat klanten een maand bijhouden hoe vaak zij dezelfde stevige tas opnieuw meenemen.~I will ask customers to record for a month how often they bring the same durable bag again.~از مشتریان می‌خواهم یک ماه ثبت کنند چند بار همان کیف بادوام را دوباره همراه می‌آورند.|De discussie over materiaal blijft onvolledig zonder informatie over echt hergebruik.~The discussion about materials remains incomplete without information about actual reuse.~بحث دربارهٔ مواد بدون اطلاعات استفادهٔ مجدد واقعی ناقص می‌ماند.
81|Ik vraag vóór vrijdag om een lijst met de ontbrekende gegevens die de beslissing echt kunnen veranderen.~I will ask before Friday for a list of the missing information that could genuinely change the decision.~پیش از جمعه فهرست داده‌های ناقصی را می‌خواهم که واقعاً ممکن است تصمیم را عوض کند.|Meer onderzoek is niet automatisch nuttig wanneer de uitkomst geen invloed op de keuze heeft.~More research is not automatically useful when its results will not affect the choice.~پژوهش بیشتر وقتی نتیجه‌اش بر انتخاب اثری نگذارد خودکار مفید نیست.
82|Ik vat bij de start van het volgende overleg eerst de reden van de andere ploeg samen.~At the start of the next meeting, I will first summarise the other team's reason.~در آغاز جلسهٔ بعد ابتدا دلیل گروه دیگر را خلاصه می‌کنم.|Een compromis houdt beter stand wanneer beide groepen zich juist begrepen voelen.~A compromise holds up better when both groups feel accurately understood.~سازش وقتی هر دو گروه احساس کنند درست فهمیده شده‌اند پایدارتر می‌ماند.
83|Ik neem de twee uur klantenopvolging voortaan zichtbaar op in de weekplanning.~I will include the two hours of customer follow-up explicitly in the weekly schedule from now on.~از این پس دو ساعت پیگیری مشتری را به‌طور مشخص در برنامهٔ هفتگی وارد می‌کنم.|Werk dat niet gepland wordt, verdwijnt gemakkelijk opnieuw achter zichtbare nieuwe taken.~Work that is not scheduled can easily disappear again behind visible new tasks.~کاری که برنامه‌ریزی نشود به‌آسانی دوباره پشت کارهای تازه و آشکار پنهان می‌شود.
84|Ik laat de ploeg de nieuwe voorraadcontrole één keer met een fictieve fout oefenen.~I will ask the team to practise the new stock check once with a fictional error.~از گروه می‌خواهم کنترل تازهٔ موجودی را یک بار با اشتباه ساختگی تمرین کند.|Een controle op papier voorkomt niets als niemand weet wanneer die moet gebeuren.~A check on paper prevents nothing if nobody knows when to carry it out.~کنترل روی کاغذ وقتی کسی نداند چه زمانی باید انجامش دهد از چیزی جلوگیری نمی‌کند.
85|Ik vraag elke thuiswerker aan het einde van de dag één duidelijke overdracht te schrijven.~I will ask every remote worker to write one clear handover at the end of the day.~از هر دورکار می‌خواهم پایان روز یک گزارش تحویل روشن بنویسد.|Flexibele uren werken beter wanneer een collega niet hoeft te wachten op ontbrekende informatie.~Flexible hours work better when a colleague does not have to wait for missing information.~ساعت‌های منعطف وقتی همکار مجبور نباشد منتظر اطلاعات ناقص بماند بهتر عمل می‌کند.
86|Ik pas de onderzoeksvraag aan zodat motivatie en beschikbare studietijd afzonderlijk worden bevraagd.~I will revise the research question so that motivation and available study time are asked about separately.~پرسش پژوهش را اصلاح می‌کنم تا انگیزه و زمان مطالعهٔ در دسترس جداگانه پرسیده شوند.|Een laag cijfer kan verschillende oorzaken hebben die een enkele vraag niet uit elkaar houdt.~A low grade may have different causes that a single question cannot distinguish.~نمرهٔ پایین می‌تواند علت‌های متفاوتی داشته باشد که یک پرسش آن‌ها را تفکیک نمی‌کند.
87|Ik vraag de buurvrouw welke beperking zij na het lezen zelf zou doorvertellen.~I will ask the neighbour which limitation she would pass on herself after reading.~از همسایه می‌پرسم پس از خواندن، خودش کدام محدودیت را برای دیگری بازگو می‌کند.|Een tekst kan eenvoudig klinken terwijl de lezer toch een te zekere conclusie onthoudt.~A text can sound simple while the reader still remembers an overly certain conclusion.~متن ممکن است ساده به نظر برسد، اما خواننده نتیجه‌ای بیش‌ازحد قطعی به خاطر بسپارد.
88|Ik zoek vóór het debat één sterke bron die mijn eigen voorstel tegenspreekt.~I will look for one strong source that contradicts my own proposal before the debate.~پیش از مناظره یک منبع قوی پیدا می‌کنم که با پیشنهاد خودم مخالفت کند.|Een zwakke tegenwerping weerleggen zegt weinig over de stevigheid van mijn argument.~Refuting a weak objection says little about the strength of my argument.~رد اعتراض ضعیف دربارهٔ استحکام استدلال من چیز زیادی نشان نمی‌دهد.
89|Ik vertel de hoofdgedachte eerst in drie zinnen en kies pas daarna één verduidelijkend voorbeeld.~I will first explain the main idea in three sentences and only then choose one clarifying example.~ابتدا نکتهٔ اصلی را در سه جمله می‌گویم و فقط بعد یک مثال روشنگر انتخاب می‌کنم.|Veel voorbeelden kunnen de structuur verbergen wanneer de kern nog niet duidelijk is.~Many examples can hide the structure when the central point is not yet clear.~وقتی اصل مطلب هنوز روشن نیست، مثال‌های زیاد ممکن است ساختار را پنهان کنند.
90|Ik laat twee proefluisteraars na mijn presentatie opschrijven welke drie kernideeën zij onthielden.~I will ask two practice listeners to write down the three main ideas they remember after my presentation.~از دو شنوندهٔ آزمایشی می‌خواهم پس از ارائهٔ من سه نکتهٔ اصلی به‌یادمانده را بنویسند.|Een spreker kan nadruk leggen op iets wat het publiek toch niet als kern herkent.~A speaker can emphasise something that the audience still does not recognise as central.~سخنران ممکن است بر چیزی تأکید کند که مخاطب همچنان آن را اصلی تشخیص ندهد.
91|Ik vraag de groep op te schrijven voor welke gevallen de aangepaste regel bedoeld is.~I will ask the group to write down which cases the revised rule is meant for.~از گروه می‌خواهم بنویسد قاعدهٔ اصلاح‌شده برای چه مواردی در نظر گرفته شده است.|Een onduidelijke uitzondering kan nieuwe ongelijkheid creëren bij de toepassing.~An unclear exception may create new inequality when applied.~استثنای مبهم ممکن است هنگام اجرا نابرابری تازه‌ای ایجاد کند.
92|Ik laat de jury eerst afzonderlijk scoren en pas daarna de verschillen bespreken.~I will ask jury members to score individually first and only then discuss differences.~از اعضای داوری می‌خواهم ابتدا جداگانه نمره دهند و بعد تفاوت‌ها را بررسی کنند.|Een vroege uitgesproken voorkeur kan de eerste indruk van andere beoordelaars sturen.~An early stated preference can influence the first impression of other judges.~ترجیحی که زود بیان شود ممکن است برداشت نخست داوران دیگر را هدایت کند.
93|Ik vraag mijn collega wat hij nu nodig heeft, zonder meteen om vergeving te vragen.~I will ask my colleague what he needs now without immediately asking for forgiveness.~از همکارم می‌پرسم اکنون به چه نیاز دارد، بدون اینکه فوراً درخواست بخشش کنم.|Een verontschuldiging draait niet alleen om de opluchting van degene die haar aanbiedt.~An apology is not only about the relief of the person offering it.~عذرخواهی فقط برای آسودگی کسی نیست که عذرخواهی می‌کند.
94|Ik splits de nieuwe planning op in één vaste belofte en één mogelijke extra taak.~I will divide the new schedule into one firm commitment and one possible extra task.~برنامهٔ تازه را به یک تعهد قطعی و یک کار اضافی احتمالی تقسیم می‌کنم.|Zo kan de ontvanger onderscheiden waarop hij kan rekenen en wat nog onzeker blijft.~That lets the recipient distinguish what they can rely on from what remains uncertain.~به این ترتیب گیرنده می‌تواند آنچه قابل‌اتکاست از آنچه هنوز نامطمئن است جدا کند.
95|Ik vraag twee vrijwilligers samen een selectievoorstel voor het archief te maken voordat iets verdwijnt.~I will ask two volunteers to prepare an archive-selection proposal together before anything is discarded.~از دو داوطلب می‌خواهم پیش از حذف هر چیز، با هم پیشنهاد گزینش بایگانی تهیه کنند.|Wat voor één persoon waardeloos lijkt, kan voor de buurt een belangrijke herinnering dragen.~What seems worthless to one person may hold an important memory for the neighbourhood.~چیزی که برای یک نفر بی‌ارزش به نظر می‌رسد ممکن است خاطره‌ای مهم برای محله داشته باشد.
96|Ik vermeld bij de brugupdate eerst dat de omleiding blijft gelden en pas daarna de verwachte datum.~I will state first in the bridge update that the diversion remains in force and only then give the expected date.~در خبر پل ابتدا می‌گویم مسیر جایگزین برقرار است و سپس تاریخ احتمالی را می‌آورم.|Lezers onthouden een opvallende datum soms als een belofte, zelfs wanneer er een voorbehoud naast staat.~Readers sometimes remember a prominent date as a promise even when a qualification appears beside it.~خوانندگان گاهی تاریخ برجسته را وعده می‌دانند، حتی اگر کنارش شرطی آمده باشد.
97|Ik toon bij de grafiek ook het verschil in euro's en leg uit waarom de schaal is aangepast.~I will also show the difference in euros beside the chart and explain why the scale was changed.~کنار نمودار تفاوت را به یورو هم نشان می‌دهم و توضیح می‌دهم چرا مقیاس عوض شده است.|Een verbeterde afbeelding moet controleerbaar zijn, niet alleen rustiger ogen.~An improved image should be verifiable, not merely look calmer.~تصویر بهبودیافته باید قابل‌بررسی باشد، نه اینکه فقط آرام‌تر به نظر برسد.
98|Ik vraag beide sprekers hun cijfers opnieuw voor hetzelfde jaar naast elkaar te zetten.~I will ask both speakers to compare their figures again for the same year.~از هر دو سخنران می‌خواهم ارقامشان را دوباره برای سال یکسان کنار هم بگذارند.|Verschillende meetperiodes kunnen op een meningsverschil lijken zonder dat de gegevens elkaar tegenspreken.~Different measurement periods can look like a disagreement without the data contradicting each other.~دوره‌های اندازه‌گیری متفاوت ممکن است اختلاف‌نظر به نظر برسد، بدون اینکه داده‌ها متناقض باشند.
99|Ik plaats onder het korte interviewfragment een verwijzing naar de aanvullende vraag en het volledige antwoord.~I will add a reference to the follow-up question and full answer beneath the short interview clip.~زیر بخش کوتاه مصاحبه، ارجاعی به پرسش تکمیلی و پاسخ کامل می‌گذارم.|Niet iedere kijker opent vanzelf een lang gesprek om ontbrekende context te zoeken.~Not every viewer automatically opens a long interview to look for missing context.~هر بیننده خودبه‌خود گفت‌وگوی طولانی را برای یافتن بافت گمشده باز نمی‌کند.
100|Ik herschrijf de titel als een mogelijk scenario en vermeld welke aanname daarvoor nodig is.~I will rewrite the headline as a possible scenario and state which assumption it depends on.~تیتر را به‌صورت سناریوی ممکن بازنویسی می‌کنم و فرض لازم برای آن را می‌آورم.|Een voorspelling wordt misleidend wanneer de voorwaarden verdwijnen en alleen de beloofde winst overblijft.~A prediction becomes misleading when its conditions disappear and only the promised profit remains.~پیش‌بینی وقتی گمراه‌کننده می‌شود که شرط‌ها حذف شوند و فقط سود وعده‌داده‌شده باقی بماند.
'''

# These questions target the second statement of each original scene. Distractors
# are later developments in the same scene, not unrelated random statements.
READING_PROMPTS = r'''
1|Wat was er met de uitnodiging van de nieuwe collega gebeurd?~What had happened to the new colleague's invitation?~برای دعوت‌نامهٔ همکار تازه چه اتفاقی افتاده بود؟
2|Over welk onderdeel van het contract had Amir nog een vraag?~Which part of the contract did Amir still have a question about?~امیر هنوز دربارهٔ کدام بخش قرارداد پرسش داشت؟
3|Waarom spraken de collega's eerst niet over de ongelijke planning?~Why did the colleagues initially not discuss the unequal schedule?~چرا همکاران ابتدا دربارهٔ برنامهٔ نامتوازن حرف نمی‌زدند؟
4|Hoe reageerde Lien op het moment dat ze haar fout ontdekte?~How did Lien react when she discovered her mistake?~لین در لحظهٔ کشف اشتباهش چه واکنشی نشان داد؟
5|Wat maakte het voor de stagiair moeilijk om zijn idee te delen?~What made it difficult for the intern to share his idea?~چه چیزی مطرح کردن ایده را برای کارآموز دشوار کرد؟
6|Welke informatie vond Nora aanvankelijk in het gemeentelijke archief?~What information did Nora initially find in the municipal archive?~نورا ابتدا چه اطلاعاتی در بایگانی شهرداری پیدا کرد؟
7|Welke verklaring overwogen de studenten eerst voor het verschil?~What explanation did the students first consider for the difference?~دانشجویان ابتدا چه توضیحی برای تفاوت در نظر گرفتند؟
8|Waarom gaf de eerste opmerking Yara weinig houvast?~Why did the first comment give Yara little guidance?~چرا نظر نخست راهنمایی چندانی به یارا نمی‌داد؟
9|Waardoor werd Jonas vooral afgeleid in de leeszaal?~What particularly distracted Jonas in the reading room?~چه چیزی به‌ویژه حواس یوناس را در سالن مطالعه پرت می‌کرد؟
10|Wat gebeurde er terwijl Mina het onbekende begrip noteerde?~What happened while Mina wrote down the unfamiliar concept?~هنگامی که مینا مفهوم ناآشنا را می‌نوشت چه اتفاقی افتاد؟
11|Waarover waren de bewoners het niet eens bij het voorstel voor de bank?~What did residents disagree about in the bench proposal?~ساکنان در پیشنهاد نیمکت دربارهٔ چه چیزی اختلاف داشتند؟
12|Welke fout werd gemaakt bij het verspreiden van de bevraging?~What mistake was made when distributing the survey?~هنگام توزیع نظرسنجی چه اشتباهی رخ داد؟
13|Welke informatie maakte de vrijwilliger bewust niet zichtbaar op de foto?~What information did the volunteer deliberately keep out of the photograph?~داوطلب عمداً چه اطلاعاتی را در عکس نشان نداد؟
14|Wat bleek toen de twee verenigingen hun wensen bespraken?~What became clear when the two associations discussed their needs?~وقتی دو انجمن نیازهایشان را مطرح کردند چه چیزی روشن شد؟
15|Welke hindernis ondervonden sommige bewoners bij de digitale aanvraag?~What obstacle did some residents face with the online application?~بعضی ساکنان در درخواست اینترنتی با چه مانعی روبه‌رو بودند؟
16|Waar dacht de huurder aanvankelijk dat het water vandaan kwam?~Where did the tenant initially think the water came from?~مستأجر ابتدا فکر می‌کرد آب از کجا آمده است؟
17|Waarover klaagden de bewoners bij het gebruik van de binnenplaats?~What did residents complain about concerning use of the courtyard?~ساکنان دربارهٔ استفاده از حیاط از چه چیزی شکایت داشتند؟
18|Welke opvallende verandering stond in Lottes verbruiksoverzicht?~What striking change appeared in Lotte's consumption statement?~چه تغییر چشمگیری در صورت مصرف لوته دیده می‌شد؟
19|Welk gevolg van de flats baarde de omwonenden zorgen?~Which consequence of the flats worried the neighbours?~کدام پیامد آپارتمان‌ها همسایه‌ها را نگران می‌کرد؟
20|Waarom gebruikte de nieuwe huisgenoot de wasmachine juist zo laat?~Why did the new housemate use the washing machine so late?~چرا هم‌خانهٔ تازه ماشین لباس‌شویی را آن‌قدر دیر استفاده می‌کرد؟
21|Wat beweerde het onderschrift over het moment waarop de foto was genomen?~What did the caption claim about when the photograph was taken?~زیرنویس دربارهٔ زمان گرفتن عکس چه ادعایی داشت؟
22|Hoe stevig was de onderzoeksbasis van de opvallende bewering?~How strong was the research basis for the striking claim?~پشتوانهٔ پژوهشی ادعای چشمگیر چقدر محکم بود؟
23|Welke indruk gaf het korte citaat van de marktkramer?~What impression did the short quotation give of the market trader?~نقل‌قول کوتاه چه برداشتی از فروشنده ایجاد می‌کرد؟
24|Welke informatie stond aanvankelijk alleen in kleine letters bij de tip?~What information initially appeared only in small print with the recommendation?~چه اطلاعاتی ابتدا فقط با حروف ریز کنار توصیه آمده بود؟
25|Met welk gevolg probeerde het dringende bericht Fatima onder druk te zetten?~What consequence did the urgent message threaten to pressure Fatima?~پیام فوری با تهدید چه پیامدی سعی داشت فاطمه را تحت فشار بگذارد؟
26|Wat belemmerde de afvoer van het water uit de kelder?~What obstructed the water drainage from the basement?~چه چیزی مانع خروج آب زیرزمین می‌شد؟
27|Waarom bleef het schoolplein lang warm?~Why did the school playground stay warm for a long time?~چرا حیاط مدرسه مدت زیادی گرم می‌ماند؟
28|Welke regeling voerde de winkelier voor de glazen flessen in?~What arrangement did the shopkeeper introduce for glass bottles?~مغازه‌دار چه ترتیبی برای بطری‌های شیشه‌ای ایجاد کرد؟
29|Welke invloed ontbrak in de eerste schatting voor de zonnepanelen?~Which influence was missing from the first estimate for the solar panels?~اثر چه چیزی در برآورد نخست پنل‌های خورشیدی در نظر گرفته نشده بود؟
30|Welke oorzaak vermoedden de wandelaars voordat het water onderzocht werd?~What cause did walkers suspect before the water was examined?~پیاده‌روها پیش از بررسی آب به چه علتی شک داشتند؟
31|Wat ging er mis bij de letterlijke vertaling van Leyla's verhaal?~What went wrong with the literal translation of Leyla's story?~در ترجمهٔ لفظی داستان لیلا چه مشکلی پیش آمد؟
32|Welk probleem meldde de bezoeker bij de ontvangst van de voorstelling?~What problem did the visitor report at the performance reception?~بازدیدکننده در پذیرش نمایش چه مشکلی گزارش کرد؟
33|Wat werd na de middag in het museum opgemerkt?~What was noticed in the museum after midday?~پس از ظهر در موزه متوجه چه چیزی شدند؟
34|Wie kwam vooral in de eerste selectie voor de tentoonstelling terecht?~Who mainly appeared in the first selection for the exhibition?~چه کسانی بیشتر در گزینش نخست نمایشگاه بودند؟
35|Welke beperking gold voor het ritueel in de sportzaal?~What restriction applied to the ritual in the sports hall?~چه محدودیتی برای آن رسم در سالن ورزش وجود داشت؟
36|Welke verleiding voelde Rob toen hij de portefeuille vond?~What temptation did Rob feel when he found the wallet?~راب هنگام پیدا کردن کیف پول چه وسوسه‌ای داشت؟
37|Waar vroeg Emma om toen haar bijdrage nauwelijks zichtbaar was?~What did Emma ask for when her contribution was barely visible?~اما وقتی سهمش تقریباً دیده نمی‌شد چه درخواستی داشت؟
38|Wat deed de omstander vlak na zijn eerste aarzeling?~What did the bystander do immediately after his first hesitation?~رهگذر درست پس از تردید اولیه چه کرد؟
39|Welke praktijk botste met het privacydoel van de sportclub?~Which practice conflicted with the sports club's privacy goal?~کدام کار با هدف حریم خصوصی باشگاه در تضاد بود؟
40|Wat bood de leverancier tegelijk met zijn verzoek aan?~What did the supplier offer alongside his request?~تأمین‌کننده همراه درخواستش چه چیزی پیشنهاد کرد؟
41|Waarover was Eva na het consult nog onzeker?~What was Eva still uncertain about after the consultation?~اوا پس از مشاوره هنوز دربارهٔ چه چیزی مطمئن نبود؟
42|Met wie besprak Pieter de belasting van zijn werk?~With whom did Pieter discuss the demands of his work?~پیتر فشار کارش را با چه کسی مطرح کرد؟
43|Wat maakte de bibliotheekingang moeilijk voor Els?~What made the library entrance difficult for Els?~چه چیزی ورودی کتابخانه را برای الس دشوار می‌کرد؟
44|Wat veranderde na enkele maanden mantelzorg voor Nadia?~What changed for Nadia after several months of caring?~پس از چند ماه مراقبت خانوادگی چه چیزی برای نادیا عوض شد؟
45|Welke eerste ondersteuning bood de begeleider Koen aan?~What initial support did the guide offer Koen?~راهنما ابتدا چه کمکی به کون پیشنهاد کرد؟
46|Waarom waren de vragen op Ramins formulier lastig?~Why were the questions on Ramin's form difficult?~چرا پرسش‌های فرم رامین دشوار بود؟
47|Voor wie was de affiche in het sportcentrum vooral bedoeld?~For whom was the poster in the sports centre mainly intended?~پوستر مرکز ورزشی بیشتر برای چه کسانی بود؟
48|Waardoor kwam er toch een afspraak voor Samira vrij?~What made an appointment become available for Samira?~چگونه با این حال زمانی برای سمیرا آزاد شد؟
49|Wat vroeg een deelnemer toen de lesgever de warming-up wilde overslaan?~What did a participant ask when the instructor wanted to skip the warm-up?~وقتی مربی می‌خواست گرم‌کردن را حذف کند، شرکت‌کننده چه پرسید؟
50|Wat vond Ilse moeilijk bij de avondberichten van haar werk?~What did Ilse find difficult about evening work messages?~ایلسه دربارهٔ پیام‌های کاری عصر چه چیزی را دشوار می‌دانست؟
51|Wat gebeurde er zes maanden na het afsluiten van Mats' abonnement?~What happened six months after Mats took out his subscription?~شش ماه پس از گرفتن اشتراک ماتس چه اتفاقی افتاد؟
52|Waarom kwam de prijs aan de kassa niet overeen met de verwachting?~Why did the checkout price not match the customer's expectation?~چرا قیمت صندوق با انتظار مشتری مطابقت نداشت؟
53|Welke kosten waren bij het buurtfeest vooral onderschat?~Which costs were particularly underestimated for the neighbourhood celebration?~کدام هزینه‌ها برای جشن محله به‌ویژه کمتر از واقع برآورد شده بود؟
54|Wat controleerde Youssef eerst op zijn betalingsbewijs?~What did Youssef first check on his payment receipt?~یوسف ابتدا چه چیزی را در رسید پرداخت بررسی کرد؟
55|Wat ontbrak bij de aanvraag voor de isolatiepremie?~What was missing from the application for the insulation grant?~در درخواست کمک‌هزینهٔ عایق‌کاری چه چیزی ناقص بود؟
56|Wat onderscheidde de goedkoopste offerte voor Noors fiets?~What distinguished the cheapest quotation for Noor's bicycle?~چه چیزی پیشنهاد ارزان‌تر برای دوچرخهٔ نور را متمایز می‌کرد؟
57|Welke aanname had de reiziger over het gewone tarief?~What assumption did the traveller make about the ordinary fare?~مسافر دربارهٔ کرایهٔ عادی چه فرضی داشت؟
58|Wat gebeurde er met Iman na een uur wachten?~What happened to Iman after an hour of waiting?~پس از یک ساعت انتظار چه اتفاقی برای ایمان افتاد؟
59|Welke voorwaarde gold voor het lenen van de boormachine?~What condition applied to borrowing the drill?~چه شرطی برای امانت گرفتن دریل وجود داشت؟
60|Wat wilden de leerlingen weten voordat ze een goed doel kozen?~What did the pupils want to know before choosing a charity?~دانش‌آموزان پیش از انتخاب خیریه می‌خواستند چه چیزی بدانند؟
61|Welke toegang vroeg de boodschappenapp naast haar eenvoudige functie?~What access did the shopping-list app request beyond its simple function?~برنامهٔ فهرست خرید جدا از قابلیت ساده‌اش چه دسترسی‌ای درخواست کرد؟
62|Welke mogelijke vertekening zag de medewerker in de selectie?~What possible bias did the employee notice in the selection?~کارمند چه سوگیری احتمالی در گزینش دید؟
63|Waarom stuurde de kaart de fietser nog naar de afgesloten brug?~Why did the map still direct the cyclist to the closed bridge?~چرا نقشه هنوز دوچرخه‌سوار را به پل بسته هدایت می‌کرد؟
64|Welk bezwaar maakte het nieuwe lid tegen het gedeelde wachtwoord?~What objection did the new member raise about the shared password?~عضو تازه چه ایرادی به گذرواژهٔ مشترک گرفت؟
65|Waarom hielp de eerste foutmelding de gebruiker nauwelijks?~Why did the first error message barely help the user?~چرا پیام خطای نخست تقریباً کمکی به کاربر نکرد؟
66|Waar liep de bediening zonder muis vast?~Where did operation without a mouse get stuck?~کار کردن بدون ماوس در کجا متوقف شد؟
67|Welk probleem gaf de vochtsensor zonder kalibratie?~What problem did the moisture sensor have without calibration?~حسگر رطوبت بدون کالیبراسیون چه مشکلی داشت؟
68|Wat stond de licentie van het gedeelde programma toe?~What did the shared program's licence allow?~مجوز برنامهٔ مشترک چه اجازه‌ای می‌داد؟
69|Welk effect van de meldingstonen merkte de groep op?~What effect of notification sounds did the group notice?~گروه متوجه چه اثری از صدای اعلان‌ها شد؟
70|Wat was het gevolg van de te lage scanresolutie?~What was the effect of the scan resolution being too low?~وضوح بسیار پایین اسکن چه پیامدی داشت؟
71|Wat was er mis met de tijdelijke halteborden?~What was wrong with the temporary bus-stop signs?~تابلوهای موقت ایستگاه چه مشکلی داشت؟
72|Wat ontdekte Bram over een medereiziger?~What did Bram discover about a fellow traveller?~برام دربارهٔ مسافر دیگری چه فهمید؟
73|Hoe verzamelde de stad gegevens over het gebruik van de fietsenstalling?~How did the city collect data about use of the bicycle parking area?~شهرداری چگونه اطلاعات استفاده از پارکینگ دوچرخه را جمع کرد؟
74|Welk gevolg had de geparkeerde bestelwagen voor de voetganger?~What consequence did the parked van have for the pedestrian?~وانت پارک‌شده چه پیامدی برای عابر داشت؟
75|Waar was de handelaar bezorgd over bij het plan voor de speelstraat?~What worried the shopkeeper about the play-street plan?~مغازه‌دار دربارهٔ طرح خیابان بازی نگران چه چیزی بود؟
76|Waarom was de onvindbare bron een probleem voor het verslag?~Why was the untraceable source a problem for the report?~چرا منبع پیدا‌نشدنی برای گزارش مشکل بود؟
77|Waardoor werd de afstandsles voor één student moeilijk te volgen?~What made the remote class difficult for one student to follow?~چه چیزی دنبال کردن کلاس از راه دور را برای یک دانشجو دشوار کرد؟
78|Waar kende één leerling de streeknaam van de plant vandaan?~From whom had one pupil learned the regional plant name?~یکی از دانش‌آموزان نام محلی گیاه را از چه کسی یاد گرفته بود؟
79|Welke tweede aanwijzing voor droogte werd naast de waterloop genoemd?~What second sign of drought was mentioned alongside the watercourse?~کنار وضعیت آبراه، چه نشانهٔ دیگری از خشکی ذکر شد؟
80|Waarover ontstond discussie toen de gratis wegwerpzak verdween?~What prompted debate when the free disposable bag disappeared?~با حذف کیسهٔ یک‌بارمصرف رایگان، دربارهٔ چه چیزی بحث شد؟
81|Welke vraag stelde de collega voordat het besluit opnieuw werd uitgesteld?~What question did the colleague raise before the decision was postponed again?~همکار پیش از تعویق دوبارهٔ تصمیم چه پرسشی مطرح کرد؟
82|Hoe stelden beide ploegen zich aan het begin van de onderhandeling op?~How did both teams position themselves at the start of the negotiation?~دو گروه در آغاز مذاکره چه موضعی داشتند؟
83|Hoe maakte de medewerker de tijd voor klantenopvolging zichtbaar?~How did the employee make time spent on customer follow-up visible?~کارمند چگونه زمان پیگیری مشتری را آشکار کرد؟
84|Waarom wilde de ploegbaas niet meteen iemand beschuldigen?~Why did the supervisor not want to accuse anyone immediately?~چرا سرپرست نمی‌خواست فوراً کسی را متهم کند؟
85|Welke afspraak maakten de collega's vóór de thuiswerkproef?~What arrangement did the colleagues make before the remote-work trial?~همکاران پیش از آزمایش دورکاری چه توافقی کردند؟
86|Wie ondervroeg de student om zijn eerste idee te onderzoeken?~Whom did the student question to investigate his initial idea?~دانشجو برای بررسی ایدهٔ نخست خود از چه کسانی پرسید؟
87|Voor welk publiek moest de onderzoeker haar uitleg veranderen?~For which audience did the researcher have to change her explanation?~پژوهشگر برای کدام مخاطبان باید توضیحش را تغییر می‌داد؟
88|Welk probleem zat er in de eerste bronnenkeuze voor het debat?~What was the problem with the first choice of sources for the debate?~انتخاب نخست منابع برای مناظره چه مشکلی داشت؟
89|Waarom hielp de eerste markering van de moeilijke tekst weinig?~Why did the initial highlighting of the difficult text help little?~چرا علامت‌گذاری نخست متن دشوار کمک کمی می‌کرد؟
90|Waar lette Daan op toen hij de opname van zijn presentatie bekeek?~What did Daan look for when watching the recording of his presentation?~دان هنگام دیدن ضبط ارائه‌اش به چه چیزی توجه کرد؟
91|Hoe verschilde de ervaring van de kleine groep van die van de meerderheid?~How did the small group's experience differ from that of the majority?~تجربهٔ گروه کوچک چه تفاوتی با تجربهٔ اکثریت داشت؟
92|Wat maakte volledig onbevooroordeeld jureren in deze wedstrijd lastig?~What made fully impartial judging difficult in this competition?~چه چیزی داوری کاملاً بی‌طرفانه را در این مسابقه دشوار می‌کرد؟
93|Hoe ervoeren beide collega's de periode na de kwetsende grap?~How did both colleagues experience the period after the hurtful joke?~دو همکار دورهٔ پس از شوخی آزاردهنده را چگونه تجربه کردند؟
94|Wat ontbrak in de oorspronkelijke planning van de vrijwilliger?~What was missing from the volunteer's original schedule?~در برنامهٔ اصلی داوطلب چه چیزی کم بود؟
95|Welke tijdelijke keuze maakte de vereniging voor het oude archief?~What temporary choice did the association make for the old archive?~انجمن برای بایگانی قدیمی چه تصمیم موقتی گرفت؟
96|Hoe zeker was de eerst genoemde openingsdatum van de brug?~How certain was the bridge's first announced opening date?~نخستین تاریخ اعلام‌شدهٔ باز شدن پل چقدر قطعی بود؟
97|Waardoor gaf de eerste grafiek een misleidende indruk?~What made the first chart give a misleading impression?~چه چیزی باعث برداشت گمراه‌کننده از نمودار نخست شد؟
98|Waarom was de tegenstelling tussen de cijfers lastig voor het publiek?~Why was the difference between the figures difficult for the audience?~چرا تفاوت ارقام برای مخاطبان دشوار بود؟
99|Hoe had de geïnterviewde haar oorspronkelijke antwoord opgebouwd?~How had the interviewee constructed her original answer?~مصاحبه‌شونده پاسخ اصلی خود را چگونه ساخته بود؟
100|Waarom was de trend in de woningprijzen moeilijk te lezen?~Why was the trend in housing prices difficult to interpret?~چرا تفسیر روند قیمت مسکن دشوار بود؟
'''

# Concise outcome sentences repair references which would otherwise lose their
# antecedent when a full reading is shortened to a one-minute spoken model.
SPOKEN_OUTCOMES = r'''
5|De proef met een aangepaste levering bespaarde verpakkingen.~The trial with an adjusted delivery process saved packaging.~آزمایش روش تحویل اصلاح‌شده در بسته‌بندی صرفه‌جویی کرد.
6|Nora gebruikte de getuigenis van een buurvrouw met toestemming als aanvulling.~Nora used a neighbour's testimony as additional material with permission.~نورا با اجازه از روایت همسایه برای تکمیل پژوهش استفاده کرد.
9|Stille uren en een aparte groepsruimte brachten verschillende leerbehoeften in evenwicht.~Quiet hours and a separate group room balanced different learning needs.~ساعت‌های سکوت و اتاق جداگانهٔ گروهی نیازهای مختلف یادگیری را متعادل کرد.
10|Een vergelijking van de spreker hielp Mina haar notities te begrijpen.~A comparison from the speaker helped Mina understand her notes.~مقایسهٔ سخنران به مینا کمک کرد یادداشت‌هایش را بفهمد.
11|Een plek naast de bibliotheek kreeg uiteindelijk voldoende steun voor de bank.~A location beside the library eventually gained sufficient support for the bench.~در نهایت جای کنار کتابخانه برای نیمکت حمایت کافی گرفت.
12|Na een langere antwoordtermijn kregen de overgeslagen bewoners ook inspraak.~After the deadline was extended, the residents who had been missed also had a say.~پس از تمدید مهلت، ساکنان جامانده هم فرصت اظهارنظر یافتند.
14|Een wisselend zaalschema bracht de twee verenigingen later tot samenwerking.~A rotating room schedule later led the two associations to cooperate.~برنامهٔ نوبتی سالن بعداً دو انجمن را به همکاری رساند.
21|Een journalist publiceerde een rechtzetting met een verwijzing naar de oudere foto.~A journalist published a correction referring to the older photograph.~روزنامه‌نگاری اصلاحیه‌ای با ارجاع به عکس قدیمی‌تر منتشر کرد.
23|De journaliste herstelde de context van de grap in het verslag.~The journalist restored the context of the joke in the report.~روزنامه‌نگار بافت شوخی را در گزارش بازگرداند.
24|Een zichtbare vermelding van de betaling hielp lezers het advies zelf beoordelen.~A visible disclosure of payment helped readers assess the recommendation themselves.~ذکر آشکار پرداخت به خوانندگان کمک کرد خودشان توصیه را ارزیابی کنند.
25|Fatima meldde het vervalste bericht en verwijderde het na controle bij de bank.~Fatima reported the forged message and deleted it after checking with the bank.~فاطمه پس از بررسی با بانک، پیام جعلی را گزارش و حذف کرد.
26|Regelmatige controle van de afvoer verkleinde het risico zonder overstromingen uit te sluiten.~Regular drainage checks reduced the risk without ruling out flooding.~بررسی منظم مجرا خطر را کم کرد، بی‌آنکه سیل را ناممکن کند.
40|De inkoper weigerde het geschenk en registreerde de afspraak om zakelijk te blijven.~The buyer refused the gift and recorded the meeting to keep the relationship professional.~خریدار هدیه را نپذیرفت و جلسه را ثبت کرد تا رابطه حرفه‌ای بماند.
41|Eva noteerde samen met de apotheker wanneer verdere opvolging nodig was.~Eva and the pharmacist recorded when further follow-up was needed.~اوا همراه داروساز زمان نیاز به پیگیری بیشتر را یادداشت کرد.
42|Pieter en zijn leidinggevende bespraken na twee weken of de pauzes vol te houden waren.~After two weeks, Pieter and his manager discussed whether the breaks could be maintained.~پیتر و مدیرش پس از دو هفته بررسی کردند آیا می‌توان استراحت‌ها را ادامه داد.
47|De woorden van een jongerenpanel maakten de affiche duidelijker.~Wording from a youth panel made the poster clearer.~واژه‌های پیشنهادی گروه جوانان پوستر را روشن‌تر کرد.
48|Samira kon de nieuwe afspraak binnen een afgesproken tijdsvenster bevestigen.~Samira could confirm the new appointment within an agreed time window.~سمیرا توانست وقت تازه را در بازهٔ توافق‌شده تأیید کند.
50|Een gezamenlijke bereikbaarheidstijd bracht rust en liet ruimte voor dringende zaken.~Shared contact hours brought peace of mind while leaving room for urgent matters.~زمان تماس مشترک آرامش آورد و برای کارهای فوری جا گذاشت.
53|De organisatoren kozen veilige voorzieningen boven extra versiering.~The organisers prioritised safe facilities over extra decorations.~برگزارکنندگان امکانات ایمن را بر تزئینات بیشتر ترجیح دادند.
54|Met zijn betalingsbewijs liet Youssef zijn cursusplaats alsnog bevestigen.~Using his payment receipt, Youssef was able to have his course place confirmed.~یوسف با رسید پرداخت توانست ثبت جای خود در دوره را تأیید کند.
58|Met een doorverwijsbriefje hoefde Iman zijn verhaal niet volledig te herhalen.~With a referral note, Iman did not have to repeat his whole story.~ایمان با برگهٔ ارجاع مجبور نشد تمام ماجرا را دوباره بگوید.
61|De gebruiker besefte dat de app ook zonder onnodige machtigingen bruikbaar bleef.~The user realised the app remained usable without unnecessary permissions.~کاربر فهمید برنامه بدون مجوزهای غیرضروری هم قابل‌استفاده می‌ماند.
69|De groep behield na een proefweek de concentratieperiode met een uitzondering voor dringende vragen.~After a trial week, the group kept the focus period with an exception for urgent questions.~گروه پس از هفتهٔ آزمایشی زمان تمرکز را با استثنای پرسش‌های فوری حفظ کرد.
72|Bram en een medereiziger bereikten dankzij een vervangbus dezelfde avond hun bestemming.~Bram and a fellow traveller reached their destination that evening using a replacement bus.~برام و مسافر دیگر با اتوبوس جایگزین همان شب به مقصد رسیدند.
73|Het verplaatsen van enkele rekken verbeterde de benutting zonder grote bijkomende kosten.~Moving some racks improved use without major additional costs.~جابه‌جایی چند پایه، استفاده را بدون هزینهٔ اضافهٔ زیاد بهتر کرد.
77|De docent bood een kort inhaalgesprek voor de student met verbindingsproblemen aan.~The lecturer offered a short catch-up conversation to the student with connection problems.~مدرس برای دانشجوی دارای مشکل اتصال، گفت‌وگوی جبرانی کوتاه پیشنهاد کرد.
84|De ploeg legde een extra voorraadcontrole vast in de normale werkwijze.~The team incorporated an extra stock check into its routine procedure.~گروه کنترل اضافهٔ موجودی را در روال عادی ثبت کرد.
85|De collega's behielden de flexibiliteit nadat ze de overdracht hadden aangepast.~The colleagues kept the flexibility after adjusting handovers.~همکاران پس از اصلاح تحویل کار، انعطاف را حفظ کردند.
90|Een oefening rond drie kernvragen hielp Daans publiek de hoofdideeën onthouden.~Practice around three key questions helped Daan's audience remember the main ideas.~تمرین حول سه پرسش اصلی به مخاطبان دان کمک کرد ایده‌های اصلی را به خاطر بسپارند.
97|De tweede grafiek met vergelijkbare assen gaf lezers een duidelijker beeld.~The second chart with comparable axes gave readers a clearer picture.~نمودار دوم با محورهای قابل‌مقایسه تصویر روشن‌تری به خوانندگان داد.
100|De lezer besloot dat ook veel cijfers de toekomst niet zeker maakten.~The reader concluded that even many figures did not make the future certain.~خواننده نتیجه گرفت حتی ارقام زیاد آینده را قطعی نمی‌کند.
'''
