"""Specific additional narrative developments for adjacent upper-stage spiral readings."""
DEVELOPMENTS = r'''
1~De vertraging voorkwam dus een grotere fout.~The delay therefore prevented a bigger mistake.~پس تأخیر از اشتباه بزرگ‌تری جلوگیری کرد.~Een administratieve vergissing had bijna de inhoudelijke kwaliteit van het besluit aangetast.~An administrative mistake had nearly undermined the quality of the decision.~اشتباهی اداری نزدیک بود کیفیت محتوایی تصمیم را تضعیف کند.
2~De aangepaste tekst vermeldde nu duidelijk de mogelijke avonddiensten.~The revised text now clearly stated the possible evening shifts.~متن اصلاح‌شده اکنون شیفت‌های عصر احتمالی را روشن ذکر می‌کرد.~De verduidelijking maakte zichtbaar welke verplichting achter een ogenschijnlijk gewone formulering schuilging.~The clarification revealed the obligation hidden behind seemingly ordinary wording.~توضیح روشن کرد چه تعهدی پشت عبارتی ظاهراً معمولی پنهان بود.
3~Ook de collega met de late diensten kon nu vooruitplannen.~The colleague with the late shifts could now plan ahead too.~همکار شیفت آخر هم اکنون می‌توانست از قبل برنامه‌ریزی کند.~Het rooster werd niet alleen gelijkmatiger, maar ook voorspelbaarder voor wie eerder weinig keuze had.~The schedule became not only more even but also more predictable for those who previously had little choice.~برنامه نه‌تنها برابرتر، بلکه برای فرد کم‌اختیارتر پیش‌بینی‌پذیرتر شد.
4~De klant wist daardoor welke versie hij moest gebruiken.~The client then knew which version to use.~مشتری به این ترتیب دانست کدام نسخه را استفاده کند.~Het erkennen van de fout bleek minder schadelijk dan het laten voortbestaan van onduidelijkheid.~Acknowledging the error proved less damaging than allowing uncertainty to persist.~پذیرفتن اشتباه کمتر از ادامهٔ ابهام آسیب‌زا بود.
5~De stagiair werd gevraagd de volgende proef mee voor te bereiden.~The intern was asked to help prepare the next trial.~از کارآموز خواسته شد در آماده‌کردن آزمایش بعدی کمک کند.~Zijn invloed groeide doordat het team een praktische toegang tot inspraak had gecreëerd.~His influence grew because the team had created a practical route to participation.~نفوذ او بیشتر شد، چون گروه راهی عملی برای مشارکت فراهم کرده بود.
6~Nora maakte duidelijk welke informatie uit het gesprek kwam.~Nora made clear which information came from the conversation.~نورا روشن کرد کدام اطلاعات از گفت‌وگو آمده است.~De herinnering verrijkte het archief zonder automatisch iedere ontbrekende historische verklaring te vervangen.~The recollection enriched the archive without automatically replacing every missing historical explanation.~خاطره بایگانی را غنی کرد، بی‌آنکه خودکار جای همهٔ توضیح‌های تاریخی مفقود را بگیرد.
7~Ze voegden de juiste instellingen aan hun verslag toe.~They added the correct settings to their report.~تنظیم‌های درست را به گزارش اضافه کردند.~Pas toen de werkomstandigheden vergelijkbaar waren, kreeg de overeenkomst tussen de resultaten betekenis.~Only when working conditions were comparable did agreement between the results become meaningful.~تنها وقتی شرایط کار قابل‌مقایسه شد، همسانی نتیجه‌ها معنا پیدا کرد.
8~Yara gebruikte de uitleg ook bij haar volgende tekst.~Yara used the explanation in her next text too.~یارا در نوشتهٔ بعدی هم از توضیح استفاده کرد.~Het gesprek verschoof de aandacht van het cijfer naar een verbeterbare redenering.~The conversation shifted attention from the grade to reasoning that could be improved.~گفت‌وگو توجه را از نمره به استدلال قابل‌بهبود منتقل کرد.
9~De stille uren stonden voortaan zichtbaar bij de ingang.~Quiet hours were now clearly displayed at the entrance.~از آن پس ساعت‌های سکوت کنار ورودی مشخص بود.~Door verschillende vormen van leren ruimte te geven, hoefde één groep de andere niet te verdringen.~Providing space for different kinds of learning prevented one group from crowding out the other.~با فراهم کردن فضا برای شیوه‌های مختلف یادگیری، لازم نبود گروهی جای دیگری را بگیرد.
10~Mina durfde bij de volgende lezing sneller om uitleg te vragen.~At the next lecture, Mina dared ask for clarification sooner.~مینا در سخنرانی بعدی زودتر جرئت کرد توضیح بخواهد.~Haar vraag legde een kennishiaat bloot dat in stilte groter zou zijn geworden.~Her question exposed a knowledge gap that would have grown in silence.~پرسش او خلأ دانشی را آشکار کرد که در سکوت بزرگ‌تر می‌شد.
11~De nieuwe bank liet het brede voetpad vrij.~The new bench left the wide pavement clear.~نیمکت تازه پیاده‌روی عریض را باز نگه داشت.~De voorkeur veranderde toen bereikbaarheid als voorwaarde voor gedeeld gebruik werd erkend.~Preferences changed once accessibility was recognised as a condition for shared use.~وقتی دسترس‌پذیری شرط استفادهٔ مشترک شناخته شد، ترجیح‌ها تغییر کردند.
12~De extra antwoorden gingen over een gevaarlijke oversteekplaats.~The additional responses concerned a dangerous crossing.~پاسخ‌های تازه دربارهٔ گذرگاهی خطرناک بودند.~De aanvulling wijzigde niet alleen het aantal reacties, maar ook welke problemen zichtbaar werden.~The addition changed not only the number of responses but also which problems became visible.~تکمیل نظرسنجی نه‌تنها تعداد پاسخ‌ها، بلکه نوع مشکلات دیده‌شده را تغییر داد.
13~De vrijwilliger verwijderde daarna zijn oproep van het bord.~The volunteer then removed his appeal from the board.~داوطلب سپس فراخوانش را از تابلو برداشت.~Het achterhouden van één herkenningsdetail maakte een zorgvuldige teruggave mogelijk zonder iedereen te wantrouwen.~Withholding one identifying detail enabled a careful return without distrusting everyone.~پنهان نگه داشتن یک نشانه امکان بازگرداندن دقیق را داد، بدون بی‌اعتمادی به همه.
14~Het vaste schema voorkwam nieuwe dubbele boekingen.~The fixed schedule prevented further double bookings.~برنامهٔ ثابت از رزروهای دوگانهٔ تازه جلوگیری کرد.~Wat als een strijd om schaarse ruimte begon, werd een aanleiding om behoeften preciezer te onderscheiden.~What began as a struggle over scarce space became an opportunity to distinguish needs more precisely.~چیزی که رقابت بر فضای کم آغاز شده بود، فرصتی برای شناخت دقیق‌تر نیازها شد.
15~Een vrijwilliger hielp zonder het formulier namens de bewoner te beslissen.~A volunteer helped without deciding the form's answers for the resident.~داوطلب کمک کرد، بدون اینکه پاسخ‌های فرم را به جای ساکن تعیین کند.~De ondersteuning vergrootte de toegang, terwijl de aanvrager eigenaar van zijn keuzes bleef.~Support widened access while the applicant retained control over their choices.~حمایت دسترسی را بیشتر کرد، درحالی‌که اختیار انتخاب نزد متقاضی ماند.
16~De huurder bewaarde foto's van voor en na de herstelling.~The tenant kept photographs from before and after the repair.~مستأجر عکس‌های قبل و بعد از تعمیر را نگه داشت.~Die documentatie scheidde de zichtbare schade van onbewezen vermoedens over de oorzaak.~That documentation separated visible damage from unproven assumptions about its cause.~آن مستندات خسارت قابل‌مشاهده را از گمان‌های اثبات‌نشده دربارهٔ علت جدا کرد.
17~De bewoners maakten eerst een kleine proefhoek met planten.~The residents first created a small trial corner with plants.~ساکنان ابتدا گوشهٔ کوچکی را آزمایشی گیاه‌کاری کردند.~Het naleven van een verbod bleek slechts de eerste stap naar een gezamenlijk gedragen bestemming.~Enforcing a ban proved only the first step towards a shared purpose.~رعایت ممنوعیت فقط گام نخست به‌سوی کاربری مورد حمایت جمع بود.
18~Lotte nam zich voor haar meter vaker te fotograferen.~Lotte decided to photograph her meter more often.~لوته تصمیم گرفت از کنتورش بیشتر عکس بگیرد.~Haar eigen registratie bood tegenwicht aan een administratief overzicht dat aanvankelijk overtuigend leek.~Her own record counterbalanced an administrative statement that had initially seemed convincing.~ثبت شخصی او در برابر صورت‌حساب اداریِ ظاهراً قانع‌کننده، مدرکی متقابل فراهم کرد.
19~De aangepaste plannen bleven voor de buren beschikbaar.~The revised plans remained available to neighbours.~نقشه‌های اصلاح‌شده در دسترس همسایه‌ها باقی ماند.~Niet alle bezwaren verdwenen, maar de beslissing maakte zichtbaar welke belangen zwaarder wogen.~Not all objections disappeared, but the decision made clear which interests carried more weight.~همهٔ اعتراض‌ها از بین نرفت، اما تصمیم روشن کرد کدام منافع وزن بیشتری داشتند.
20~De late werknemer kreeg op zijn vrije dag extra wastijd.~The late-shift worker received extra laundry time on his day off.~کارگر شیفت آخر در روز آزاد وقت بیشتری برای لباس‌شویی گرفت.~De regeling hield rekening met ongelijke werkuren zonder nachtrust als bijkomstigheid te behandelen.~The arrangement recognised unequal working hours without treating sleep as incidental.~توافق تفاوت ساعت کاری را در نظر گرفت، بدون کم‌اهمیت دانستن خواب شب.
21~Verschillende lezers deelden daarna ook de verbeterde informatie.~Several readers then shared the corrected information too.~چند خواننده بعداً اطلاعات اصلاح‌شده را هم بازنشر کردند.~De kracht van het beeld bleef bestaan, maar de vermeende actualiteit ervan viel weg.~The image retained its impact, but its supposed immediacy disappeared.~تأثیر تصویر باقی ماند، اما تازگی ادعایی آن از بین رفت.
22~Het artikel maakte nu duidelijk dat verder onderzoek nodig was.~The article now made clear that further research was needed.~مقاله اکنون روشن می‌کرد پژوهش بیشتری لازم است.~De correctie ontkende de studie niet, maar beperkte wat er redelijkerwijs uit afgeleid kon worden.~The correction did not reject the study but limited what could reasonably be inferred from it.~اصلاح، پژوهش را رد نکرد، بلکه نتیجه‌گیری معقول از آن را محدود کرد.
23~De marktkramer kreeg de aangepaste passage toegestuurd.~The trader received the revised passage.~بخش اصلاح‌شده برای فروشنده فرستاده شد.~Een letterlijk juist citaat bleek zonder context toch een scheef beeld te kunnen geven.~A literally accurate quotation nevertheless proved capable of creating a distorted impression without context.~نقل‌قول لفظاً درست، بدون بافت می‌توانست تصویری نادرست بسازد.
24~Lezers konden de betaalde tip nu meteen herkennen.~Readers could now immediately recognise the paid recommendation.~خوانندگان اکنون توصیهٔ پولی را فوری تشخیص می‌دادند.~Openheid over betaling loste mogelijke beïnvloeding niet op, maar maakte haar wel beoordeelbaar.~Disclosure of payment did not remove possible influence but made it open to scrutiny.~افشای پرداخت تأثیر احتمالی را حذف نکرد، اما امکان سنجش آن را داد.
25~De bank bevestigde dat ze nooit via die bijlage om gegevens vroeg.~The bank confirmed it never requested details through that attachment.~بانک تأیید کرد هرگز از راه آن پیوست اطلاعات نمی‌خواهد.~De tijdsdruk in het bericht bleek precies het middel om een onafhankelijke controle te verhinderen.~The message's urgency was precisely the means used to prevent independent checking.~فشار زمانی پیام دقیقاً ابزاری برای جلوگیری از بررسی مستقل بود.
26~De bewoners verdeelden de controle over verschillende huisgenoten.~The residents shared the checks among different housemates.~ساکنان بررسی را میان هم‌خانه‌ها تقسیم کردند.~De maatregel behandelde een beïnvloedbare oorzaak zonder zekerheid over extreem weer te suggereren.~The measure addressed a controllable cause without implying certainty about extreme weather.~اقدام علت قابل‌کنترل را هدف گرفت، بدون ادعای قطعیت دربارهٔ آب‌وهوای شدید.
27~De eerste zomer zochten leerlingen er meteen de schaduw op.~In the first summer, pupils immediately sought shade there.~در نخستین تابستان، دانش‌آموزان همان‌جا به سایه رفتند.~Het groenplan werd pas uitvoerbaar toen ecologische wensen met de technische draagstructuur werden verzoend.~The greening plan became feasible only when environmental wishes were reconciled with the technical structure.~طرح سبز وقتی اجراپذیر شد که خواست محیط‌زیستی با سازهٔ فنی سازگار شد.
28~De winkel hield apart bij hoeveel flessen beschadigd terugkwamen.~The shop separately recorded how many bottles returned damaged.~فروشگاه تعداد بطری‌های آسیب‌دیدهٔ برگشتی را جدا ثبت کرد.~Het succes hing niet alleen af van materiaal, maar ook van retourgedrag en bruikbare flessen.~Success depended not only on material but also on return behaviour and usable bottles.~موفقیت فقط به جنس وابسته نبود، بلکه به رفتار بازگرداندن و سلامت بطری‌ها هم بستگی داشت.
29~De aangepaste berekening werd naast de eerste schatting bewaard.~The revised calculation was kept beside the first estimate.~محاسبهٔ اصلاح‌شده کنار برآورد اول نگهداری شد.~Een bescheidener verwachting maakte de investering geloofwaardiger dan een onhoudbare belofte van snelle winst.~A more modest expectation made the investment more credible than an unsustainable promise of quick returns.~انتظاری فروتنانه‌تر سرمایه‌گذاری را معتبرتر از وعدهٔ بی‌پایهٔ سود سریع کرد.
30~De dienst bleef het water volgen terwijl de temperatuur veranderde.~The service continued monitoring the water as the temperature changed.~اداره با تغییر دما به پایش آب ادامه داد.~Het onderzoek verschoof van het aanwijzen van een schuldige naar het onderscheiden van mogelijke oorzaken.~The investigation shifted from naming a culprit to distinguishing possible causes.~بررسی از تعیین مقصر به تشخیص علت‌های ممکن تغییر کرد.
31~Leyla vertelde later waarom ze niet elk woord letterlijk had vertaald.~Leyla later explained why she had not translated every word literally.~لیلا بعداً توضیح داد چرا همهٔ واژه‌ها را لفظی ترجمه نکرده است.~De ingreep veranderde de vorm om juist de sociale werking van de oorspronkelijke grap te behouden.~The change altered the form precisely to preserve the social effect of the original joke.~تغییر شکل دقیقاً برای حفظ کارکرد اجتماعی شوخی اصلی بود.
32~De lijst werd meteen aangepast om een tweede vergissing te vermijden.~The list was immediately corrected to avoid another mistake.~فهرست فوری اصلاح شد تا اشتباه دیگری رخ ندهد.~De bevestiging bood een controleerbaar aanknopingspunt waar een mondelinge herinnering onzeker was gebleven.~The confirmation provided verifiable evidence where an oral recollection would have remained uncertain.~تأییدیه مدرکی قابل‌بررسی فراهم کرد، جایی که یادآوری شفاهی نامطمئن می‌ماند.
33~Het gereedschap lag veilig in een pas verplaatste lade.~The tool was safe in a recently moved drawer.~ابزار در کشویی که تازه جابه‌جا شده بود سالم قرار داشت.~Door een praktische verklaring te onderzoeken, voorkwam het team dat wantrouwen de samenwerking beschadigde.~Investigating a practical explanation prevented distrust from damaging cooperation.~بررسی توضیحی عملی مانع آسیب بی‌اعتمادی به همکاری شد.
34~De nieuwe makers brachten ook een ander publiek mee.~The new artists also brought a different audience.~هنرمندان تازه مخاطبان دیگری هم آوردند.~De selectie werd breder doordat de toegang tot deelname veranderde, niet doordat kwaliteit werd losgelaten.~The selection widened because access to participation changed, not because quality was abandoned.~گزینش گسترده‌تر شد چون راه مشارکت تغییر کرد، نه چون کیفیت کنار گذاشته شد.
35~De lampjes werden samen met het verhaal over de kaarsen getoond.~The lamps were presented together with the story about the candles.~چراغ‌ها همراه توضیح سنت شمع نشان داده شدند.~Het alternatief behield de betekenis van het ritueel terwijl de praktische veiligheidsgrens overeind bleef.~The alternative preserved the ritual's meaning while maintaining the practical safety boundary.~جایگزین معنای آیین را حفظ کرد، درحالی‌که مرز ایمنی برقرار ماند.
36~Rob hoefde geen beloning om tevreden te zijn over zijn keuze.~Rob needed no reward to feel satisfied with his choice.~روب برای رضایت از انتخابش به پاداش نیاز نداشت.~Het onbekende gezicht achter de portefeuille werd voor hem belangrijker dan een onmiddellijk eigen voordeel.~The unknown person behind the wallet became more important to him than an immediate personal gain.~فرد ناشناسِ صاحب کیف برای او مهم‌تر از سود فوری خودش شد.
37~Voortaan hield het team de taakverdeling tijdens het werk bij.~From then on, the team recorded contributions while working.~از آن پس گروه هنگام کار تقسیم وظایف را ثبت می‌کرد.~De erkenning werd daarmee een onderdeel van het proces in plaats van een onderhandeling achteraf.~Recognition thus became part of the process rather than a negotiation afterwards.~به این ترتیب به‌رسمیت‌شناختن سهم بخشی از روند شد، نه مذاکرهٔ پایانی.
38~De omstander bleef tot het familielid aankwam.~The bystander stayed until the family member arrived.~رهگذر تا رسیدن عضو خانواده ماند.~Zijn betrokkenheid bood steun zonder de beslissingsruimte van de gevallen fietser over te nemen.~His involvement offered support without taking over the fallen cyclist's decisions.~مشارکتش حمایت کرد، بدون گرفتن اختیار تصمیم از دوچرخه‌سوار.
39~Aan de ingang bleef alleen algemene clubinformatie hangen.~Only general club information remained at the entrance.~کنار ورودی فقط اطلاعات عمومی باشگاه باقی ماند.~De club onderscheidde voortaan wat organisatorisch handig was van wat openbaar noodzakelijk was.~The club now distinguished administrative convenience from what needed to be public.~باشگاه از آن پس راحتی اداری را از ضرورت عمومی‌بودن جدا کرد.
40~De inkoper liet de kwaliteit van het aanbod apart beoordelen.~The buyer had the quality of the offer assessed separately.~مسئول خرید کیفیت پیشنهاد را جداگانه ارزیابی کرد.~Zo bleef ook de schijn van een persoonlijke tegenprestatie buiten de zakelijke beslissing.~This also kept the appearance of a personal favour out of the business decision.~به این ترتیب حتی شائبهٔ لطف شخصی از تصمیم حرفه‌ای دور ماند.
41~Eva schreef de belangrijkste instructies in haar eigen woorden op.~Eva wrote the main instructions in her own words.~اوا دستورهای اصلی را با واژه‌های خودش نوشت.~De extra vraag maakte onderscheid tussen beschikbare informatie en informatie die werkelijk begrepen was.~The extra question distinguished available information from information that was actually understood.~پرسش اضافی میان اطلاعات موجود و اطلاعات واقعاً فهمیده‌شده تمایز گذاشت.
42~De pauze bleef ook op drukke dagen in de agenda staan.~The break stayed in the diary even on busy days.~استراحت حتی در روزهای شلوغ در برنامه ماند.~De verandering legde herstel niet uitsluitend bij persoonlijke wilskracht, maar ook bij de organisatie van het werk.~The change located recovery not solely in personal willpower but also in the organisation of work.~تغییر، تجدید قوا را فقط به ارادهٔ فردی نسبت نداد، بلکه به سازمان‌دهی کار هم مربوط کرد.
43~Ook andere bezoekers maakten gebruik van de duidelijkere route.~Other visitors also used the clearer route.~مراجعه‌کنندگان دیگر هم از مسیر روشن‌تر استفاده کردند.~Een voorziening werd pas praktisch toegankelijk toen de weg ernaartoe eveneens begrijpelijk was.~A facility became practically accessible only when the route to it was understandable too.~امکان وقتی عملاً دسترس‌پذیر شد که مسیر رسیدن به آن هم روشن بود.
44~Nadia gebruikte de vrije middag soms gewoon om uit te rusten.~Nadia sometimes used the free afternoon simply to rest.~نادیا گاهی بعدازظهر آزاد را فقط استراحت می‌کرد.~Hulp betekende hier geen volledige overname, maar een verdeling die langer vol te houden was.~Help here meant not complete replacement but a distribution that could be sustained longer.~کمک اینجا جایگزینی کامل نبود، بلکه تقسیمی بود که دوام بیشتری داشت.
45~Koen schreef zich daarna zelf voor een volgende wandeling in.~Koen then signed himself up for another walk.~کون بعداً خودش برای پیاده‌روی دیگری ثبت‌نام کرد.~De persoonlijke kennismaking verlaagde een sociale hindernis zonder zijn keuzevrijheid weg te nemen.~The personal introduction lowered a social barrier without removing his freedom of choice.~آشنایی شخصی مانع اجتماعی را کم کرد، بدون از بین بردن آزادی انتخاب.
46~Ramin liet de vragen die hij niet begreep eerst toelichten.~Ramin first had the questions he did not understand explained.~رامین ابتدا توضیح پرسش‌هایی را که نمی‌فهمید خواست.~Zijn medewerking werd betekenisvoller toen zij berustte op begrip in plaats van op stilzwijgende volgzaamheid.~His cooperation became more meaningful when based on understanding rather than silent compliance.~همکاری او وقتی بر فهم استوار شد معنادارتر از اطاعت خاموش بود.
47~De nieuwe affiche gebruikte kortere zinnen en concrete situaties.~The new poster used shorter sentences and concrete situations.~پوستر تازه جمله‌های کوتاه‌تر و موقعیت‌های مشخص داشت.~De makers toetsten hun taalkeuzes aan de lezers voor wie de boodschap bedoeld was.~The creators tested their language choices with the readers the message was meant for.~سازندگان انتخاب زبانی را با همان خوانندگانی آزمودند که مخاطب پیام بودند.
48~De praktijk noteerde haar voorkeur zonder extra persoonlijke details te vragen.~The practice recorded her preference without asking for extra personal details.~مطب ترجیح او را ثبت کرد، بدون پرسیدن جزئیات شخصی اضافی.~Betere bereikbaarheid kwam voort uit een passende afspraak, niet uit de verwachting dat iemand altijd beschikbaar is.~Better contact came from a suitable arrangement, not the expectation of constant availability.~تماس بهتر از توافق مناسب حاصل شد، نه انتظارِ همیشه در دسترس بودن.
49~De deelnemers konden voortaan tussen twee oefeningen kiezen.~Participants could now choose between two exercises.~شرکت‌کنندگان از آن پس می‌توانستند میان دو تمرین انتخاب کنند.~De les werd inclusiever doordat verschillen in belastbaarheid als vertrekpunt werden genomen.~The class became more inclusive by taking differences in physical capacity as a starting point.~کلاس فراگیرتر شد چون تفاوت توان فعالیت نقطهٔ آغاز قرار گرفت.
50~Voor noodgevallen bleef één duidelijk contactkanaal bestaan.~One clear contact channel remained for emergencies.~برای موارد اضطراری یک راه تماس روشن باقی ماند.~Door urgentie af te bakenen, verloor voortdurende bereikbaarheid haar schijnbare vanzelfsprekendheid.~Defining urgency removed the apparent inevitability of constant availability.~با تعریف فوریت، همیشه در دسترس بودن دیگر بدیهی به نظر نمی‌رسید.
'''
DEVELOPMENTS += r'''
51~Mats bewaarde de bevestiging van zijn opzegging.~Mats kept the confirmation of his cancellation.~ماتس تأیید فسخ را نگه داشت.~De aantrekkelijke instapprijs had de totale duur en kosten van de overeenkomst naar de achtergrond geduwd.~The attractive initial price had pushed the agreement's total duration and cost into the background.~قیمت اولیهٔ جذاب مدت و هزینهٔ کلی توافق را به حاشیه برده بود.
52~De winkel verplaatste het foutieve bord naar het juiste rek.~The shop moved the misplaced sign to the correct rack.~فروشگاه تابلو را به قفسهٔ درست منتقل کرد.~Een individuele tegemoetkoming loste het gesprek op, terwijl de gewijzigde presentatie herhaling moest voorkomen.~An individual concession resolved the discussion, while changed presentation was meant to prevent recurrence.~امتیاز فردی گفت‌وگو را حل کرد، درحالی‌که اصلاح نمایش قیمت باید از تکرار جلوگیری می‌کرد.
53~Ze leenden versiering van een naburige vereniging.~They borrowed decorations from a neighbouring association.~تزیینات را از انجمن همسایه قرض گرفتند.~De beperktere middelen dwongen hen het doel van het feest boven bijkomende uitstraling te plaatsen.~Limited resources forced them to prioritise the party's purpose over extra visual appeal.~منابع محدود آنان را واداشت هدف جشن را بر جلوهٔ اضافی ترجیح دهند.
54~Youssef noteerde de juiste mededeling voor een volgende betaling.~Youssef noted the correct reference for a future payment.~یوسف شرح درست را برای پرداخت بعدی یادداشت کرد.~Het geld was niet verdwenen; het probleem lag in de administratieve herkenning van de transactie.~The money had not disappeared; the problem lay in identifying the transaction administratively.~پول ناپدید نشده بود؛ مشکل در شناسایی اداری تراکنش بود.
55~Het gezin diende de ontbrekende factuur binnen die termijn in.~The family submitted the missing invoice within that period.~خانواده فاکتور مفقود را در همان مهلت ارائه کرد.~De kans op aanvulling voorkwam dat een herstelbaar administratief gebrek meteen tot uitsluiting leidde.~The opportunity to add documents prevented a correctable administrative omission from immediately causing exclusion.~فرصت تکمیل مانع شد نقص اداری قابل‌اصلاح فوراً به محرومیت بینجامد.
56~Noor vroeg de afspraken ook op de werkbon te zetten.~Noor asked for the terms to be included on the work order too.~نور خواست توافق‌ها روی برگهٔ کار هم ثبت شود.~Haar keuze verschoof van de laagste onmiddellijke prijs naar de verwachte waarde over een langere periode.~Her choice shifted from the lowest immediate price to expected value over a longer period.~انتخاب از پایین‌ترین قیمت فوری به ارزش مورد انتظار در مدت طولانی‌تر تغییر کرد.
57~Hij bewaarde de nieuwe uitleg samen met zijn kaart.~He kept the new explanation with his card.~توضیح تازه را کنار کارت نگه داشت.~Een prijsvergelijking bleek pas zinvol wanneer ook de gebruiksvoorwaarden van elke formule zichtbaar waren.~A price comparison became meaningful only when each option's conditions were visible too.~مقایسهٔ قیمت تنها وقتی معنادار شد که شرایط استفادهٔ هر گزینه نیز روشن بود.
58~Het briefje vermeldde welke documenten al gecontroleerd waren.~The note stated which documents had already been checked.~برگه مشخص می‌کرد کدام مدارک قبلاً بررسی شده‌اند.~De oplossing verbeterde de samenhang tussen diensten zonder hun afzonderlijke bevoegdheden te ontkennen.~The solution improved coordination between services without denying their separate responsibilities.~راه‌حل پیوستگی خدمات را بهتر کرد، بدون انکار اختیارهای جداگانهٔ آن‌ها.
59~Voor grote schade bleef een afzonderlijk gesprek nodig.~Major damage still required a separate discussion.~برای خسارت بزرگ همچنان گفت‌وگویی جدا لازم بود.~Het onderscheid tussen slijtage en nalatigheid beschermde zowel de gebruikers als het gedeelde materiaal.~Distinguishing wear from negligence protected both users and shared equipment.~تمایز فرسودگی از سهل‌انگاری هم کاربران و هم ابزار مشترک را محافظت کرد.
60~De leerlingen legden hun keuze aan de andere klassen uit.~The pupils explained their choice to the other classes.~دانش‌آموزان انتخابشان را برای کلاس‌های دیگر توضیح دادند.~Hun beoordeling betrok de maatschappelijke opbrengst, in plaats van efficiëntie tot één kostenpercentage te herleiden.~Their assessment included social impact rather than reducing efficiency to a single cost percentage.~ارزیابی اثر اجتماعی را در نظر گرفت، به‌جای تقلیل کارایی به یک درصد هزینه.
61~Hij kon zijn boodschappenlijst nog steeds gewoon bijwerken.~He could still update his shopping list normally.~هنوز می‌توانست فهرست خرید را عادی به‌روز کند.~Het weigeren van brede toegang toonde dat gevraagde gegevens niet noodzakelijk functioneel vereist waren.~Refusing broad access showed that requested data were not necessarily functionally required.~نپذیرفتن دسترسی گسترده نشان داد دادهٔ درخواستی لزوماً برای عملکرد ضروری نیست.
62~Afgewezen kandidaten kregen opnieuw een menselijke beoordeling.~Rejected candidates received a new human review.~متقاضیان ردشده دوباره بررسی انسانی شدند.~Een efficiënte rangschikking bleek geen voldoende reden om verborgen selectiemechanismen zonder onderzoek te aanvaarden.~Efficient ranking proved insufficient reason to accept hidden selection mechanisms without scrutiny.~رتبه‌بندی کارآمد دلیل کافی برای پذیرش سازوکار پنهان انتخاب بدون بررسی نبود.
63~De kaart werd later met de tijdelijke afsluiting bijgewerkt.~The map was later updated with the temporary closure.~نقشه بعداً با اطلاعات بسته‌شدن موقت به‌روز شد.~De melding van één gebruiker maakte een verschil tussen de digitale voorstelling en de veranderde werkelijkheid zichtbaar.~One user's report exposed a gap between the digital representation and changed reality.~گزارش یک کاربر فاصلهٔ نمایش دیجیتال و واقعیت تغییرکرده را آشکار کرد.
64~Het papier met het oude wachtwoord werd verwijderd.~The paper with the old password was removed.~کاغذ رمز قدیمی برداشته شد.~Persoonlijke toegang maakte verantwoordelijkheden duidelijker dan een gedeeld geheim waarvan niemand de verspreiding kende.~Individual access clarified responsibility more than a shared secret whose circulation nobody knew.~دسترسی شخصی مسئولیت را روشن‌تر از رازی مشترک با دامنهٔ انتشار نامعلوم کرد.
65~De beheerder liet voortaan zien wanneer antwoorden opgeslagen waren.~The administrator began showing when answers had been saved.~مدیر از آن پس زمان ذخیرهٔ پاسخ‌ها را نشان داد.~Herstel van gegevens en begrijpelijke communicatie bleken twee verschillende voorwaarden voor vertrouwen.~Data recovery and understandable communication proved two distinct conditions for trust.~بازیابی داده و ارتباط روشن دو شرط جداگانه برای اعتماد بودند.
66~De verbetering werd ook op een andere pagina getest.~The improvement was tested on another page too.~بهبود در صفحه‌ای دیگر نیز آزمایش شد.~De fout werd pas zichtbaar toen een gebruikswijze buiten die van de ontwikkelaar serieus werd genomen.~The defect became visible only when a way of using the site unlike the developer's was taken seriously.~خطا وقتی آشکار شد که شیوهٔ استفاده‌ای متفاوت از توسعه‌دهنده جدی گرفته شد.
67~De vereniging herhaalde de vergelijking enkele weken later.~The association repeated the comparison a few weeks later.~انجمن چند هفته بعد مقایسه را تکرار کرد.~Een meetwaarde kreeg pas praktische betekenis nadat de relatie met een betrouwbare referentie was gecontroleerd.~A measurement gained practical meaning only after its relation to a reliable reference was checked.~عدد اندازه‌گیری وقتی معنا یافت که رابطه‌اش با مرجع معتبر بررسی شد.
68~Nieuwe vrijwilligers vonden nu ook uitleg over het installeren.~New volunteers could now also find installation instructions.~داوطلبان تازه اکنون راهنمای نصب را هم پیدا می‌کردند.~Open beschikbaarheid van code leidde dus niet vanzelf tot bruikbaarheid zonder overdraagbare kennis.~Open access to code did not therefore automatically create usability without transferable knowledge.~دسترسی باز به کد بدون دانش قابل‌انتقال خودبه‌خود به قابل‌استفاده بودن نینجامید.
69~Dringende berichten kregen één herkenbaar kanaal.~Urgent messages received one recognisable channel.~پیام‌های فوری یک راه مشخص پیدا کردند.~De afspraak maakte een onderscheid tussen snelle bereikbaarheid en de kwaliteit van ononderbroken aandacht.~The agreement distinguished rapid contactability from the quality of uninterrupted attention.~توافق میان تماس سریع و کیفیت توجه بی‌وقفه تمایز گذاشت.
70~Sofie voegde bij elke foto de bekende namen en jaartallen toe.~Sofie added known names and years to each photograph.~سوفی نام‌ها و سال‌های شناخته‌شده را به هر عکس افزود.~Duurzame bewaring betrof daarmee zowel het beeldbestand als de context die het later begrijpelijk maakt.~Long-term preservation thus covered both the image file and the context that makes it understandable later.~نگهداری پایدار هم فایل تصویر و هم بافتی را شامل شد که بعداً آن را قابل‌فهم می‌کند.
71~Ook het bericht op de website kreeg de nieuwe richting.~The website notice also received the new directions.~اطلاعیهٔ وب‌سایت هم جهت تازه را نشان داد.~Informatie werd pas bruikbaar wanneer zij vanuit het perspectief van de aankomende reiziger leesbaar was.~Information became usable only when readable from the arriving traveller's perspective.~اطلاعات وقتی کاربردی شد که از دید مسافرِ در حال رسیدن قابل‌خواندن بود.
72~De reizigers hielden hun tickets bij voor eventuele verdere vragen.~The travellers kept their tickets for any further enquiries.~مسافران بلیت‌ها را برای پرسش‌های احتمالی بعدی نگه داشتند.~Het gedeelde probleem maakte samenwerking mogelijk zonder dat zij vooraf dezelfde reisplannen hadden gehad.~The shared problem enabled cooperation without their having had identical travel plans beforehand.~مشکل مشترک همکاری را ممکن کرد، بدون اینکه پیش‌تر برنامهٔ سفر یکسان داشته باشند.
73~De stad volgde na de verplaatsing opnieuw de bezetting.~The city monitored occupancy again after moving the racks.~شهر پس از جابه‌جایی دوباره نرخ اشغال را بررسی کرد.~De ingreep liet zien dat capaciteit en bruikbare capaciteit niet noodzakelijk hetzelfde zijn.~The intervention showed that capacity and usable capacity are not necessarily the same.~اقدام نشان داد ظرفیت و ظرفیت قابل‌استفاده لزوماً یکی نیستند.
74~De chauffeur vertelde ook zijn collega's over de laadzone.~The driver also told his colleagues about the loading zone.~راننده به همکارانش هم دربارهٔ محل بارگیری گفت.~Een korte verplaatsing bracht het gemak van levering beter in verhouding tot de bewegingsruimte van anderen.~A short move better balanced delivery convenience with others' freedom to move.~جابه‌جایی کوتاه، راحتی تحویل را با فضای حرکت دیگران متعادل‌تر کرد.
75~Bewoners en handelaars hielden de ervaringen gezamenlijk bij.~Residents and traders jointly recorded their experiences.~ساکنان و فروشندگان تجربه‌ها را مشترک ثبت کردند.~Een tijdelijk experiment verminderde de druk om vooraf tussen volledige aanvaarding en volledige afwijzing te kiezen.~A temporary trial reduced pressure to choose beforehand between total acceptance and total rejection.~آزمایش موقت فشار انتخاب پیشاپیش میان پذیرش کامل و رد کامل را کم کرد.
76~De auteur controleerde daarna ook de andere verwijzingen.~The author then checked the other references too.~نویسنده سپس ارجاع‌های دیگر را هم بررسی کرد.~De inhoudelijke kracht van een bron bleef moeilijk beoordeelbaar zolang de bron zelf niet traceerbaar was.~The substantive strength of a source remained hard to assess while the source itself was untraceable.~تا وقتی خود منبع یافت‌شدنی نبود، ارزیابی قوت محتوایی آن دشوار می‌ماند.
77~De student kon zijn resterende vragen in dat gesprek stellen.~The student could ask the remaining questions during that conversation.~دانشجو توانست پرسش‌های باقی‌مانده را در آن گفت‌وگو بپرسد.~Een technisch kanaal alleen garandeerde geen gelijke deelname; een herstelbare interactie was evenzeer nodig.~A technical channel alone did not guarantee equal participation; recoverable interaction was needed too.~کانال فنی به‌تنهایی مشارکت برابر را تضمین نکرد؛ فرصت جبران تعامل نیز لازم بود.
78~Bij elk plantenbord kwamen voortaan beide namen te staan.~Both names were subsequently displayed on each plant label.~از آن پس هر دو نام روی تابلوی گیاه نوشته شد.~De klas kon variatie waarderen en tegelijk bespreken in welke context een standaardterm nuttig is.~The class could value variation while discussing where a standard term is useful.~کلاس توانست تنوع را ارزشمند بداند و هم‌زمان کاربرد اصطلاح معیار را بررسی کند.
79~De betrokkenen spraken af de waterstanden samen op te volgen.~Those involved agreed to monitor water levels together.~افراد درگیر توافق کردند سطح آب را مشترک پایش کنند.~De beek werd zo een gedeelde opgave in plaats van uitsluitend een probleem aan één perceelsgrens.~The stream became a shared challenge rather than a problem at one plot boundary.~جویبار به مسئله‌ای مشترک تبدیل شد، نه فقط مشکلی کنار مرز یک زمین.
80~De winkel plaatste een herinnering bij de ingang.~The shop placed a reminder at the entrance.~فروشگاه یادآوری‌ای کنار ورودی نصب کرد.~De materiaalvergelijking kreeg pas betekenis toen ook herhaald gebruik in de afweging werd betrokken.~The material comparison became meaningful only when repeated use was included in the assessment.~مقایسهٔ جنس وقتی معنادار شد که استفادهٔ مکرر هم وارد سنجش شد.
81~De beslissing werd meteen met de betrokken collega's gedeeld.~The decision was immediately shared with the colleagues involved.~تصمیم فوری با همکاران مربوطه در میان گذاشته شد.~De afgesproken grens maakte duidelijk dat extra zekerheid ook kosten in tijd en stilstand heeft.~The agreed limit made clear that additional certainty also has costs in time and delay.~حد توافق‌شده روشن کرد قطعیت بیشتر نیز هزینهٔ زمان و توقف دارد.
82~Na twee weken bleek één overdrachtsmoment nog onhandig.~After two weeks, one handover time still proved awkward.~پس از دو هفته یک زمان تحویل کار هنوز نامناسب بود.~Het akkoord bleef daarom een werkbare afspraak die bijgesteld kon worden, geen overwinning van één ploeg.~The agreement remained an adjustable working arrangement rather than a victory for one team.~توافق ترتیبی عملی و اصلاح‌پذیر ماند، نه پیروزی یک گروه.
83~De volgende planning reserveerde expliciet tijd voor klantenopvolging.~The next schedule explicitly reserved time for customer follow-up.~برنامهٔ بعدی صریحاً زمانی برای پیگیری مشتریان گذاشت.~Door werk zichtbaar te maken, werd een individueel ervaren tijdsprobleem een bespreekbare organisatievraag.~Making work visible turned an individually felt time problem into a discussable organisational issue.~با آشکارکردن کار، مشکل زمانِ فردی به مسئلهٔ سازمانی قابل‌گفت‌وگو تبدیل شد.
84~Nieuwe collega's leerden de controle tijdens hun eerste werkweek.~New colleagues learned the check in their first working week.~همکاران تازه بررسی را در هفتهٔ اول کار یاد گرفتند.~De aanpak verplaatste de aandacht van persoonlijke schuld naar de omstandigheden die fouten herhaalbaar maakten.~The approach moved attention from personal blame to conditions that made errors repeatable.~رویکرد توجه را از تقصیر شخصی به شرایطی منتقل کرد که تکرار خطا را ممکن می‌کردند.
85~Een vast gedeeld overzicht maakte die overdracht eenvoudiger.~A regular shared overview made the handover easier.~نمای مشترک ثابت، تحویل کار را آسان‌تر کرد.~De proef leverde geen universeel oordeel over thuiswerk op, maar een beter passende regeling voor dit team.~The trial produced no universal verdict on remote work, but a better-fitting arrangement for this team.~آزمایش حکمی کلی دربارهٔ دورکاری نداد، بلکه توافق مناسب‌تری برای این گروه ساخت.
86~Hij nam verschillen in beschikbare tijd op in zijn analyse.~He included differences in available time in his analysis.~تفاوت زمان موجود را وارد تحلیل کرد.~De tegenvoorbeelden verzwakten niet het onderzoek, maar wel de aanspraak van zijn eerste verklaring op algemeen geldige waarheid.~The counterexamples weakened not the research but the first explanation's claim to universal truth.~مثال‌های مخالف پژوهش را ضعیف نکردند، بلکه ادعای حقیقت عمومیِ توضیح نخست را تضعیف کردند.
87~De buurvrouw wees één onduidelijke vergelijking aan.~The neighbour identified one unclear comparison.~همسایه یک مقایسهٔ نامفهوم را نشان داد.~Toegankelijke taal bleek geen vrijblijvende verkorting, maar een nieuwe verantwoordelijkheid voor dezelfde inhoud.~Accessible language proved not merely optional shortening but a renewed responsibility for the same content.~زبان روشن فقط کوتاه‌سازی دلخواه نبود، بلکه مسئولیتی تازه برای همان محتوا بود.
88~Hij vermeldde het sterkste bezwaar ook in zijn slotwoord.~He included the strongest objection in his closing statement too.~قوی‌ترین اعتراض را در سخن پایانی هم ذکر کرد.~Een standpunt werd sterker doordat het weerstand kon verwerken, niet doordat tegenspraak buiten beeld bleef.~A position grew stronger by absorbing challenge, not by keeping disagreement out of view.~موضع از توان پردازش مخالفت قوی‌تر شد، نه از پنهان‌ماندن آن.
89~Een medecursist herkende de drie hoofdpunten in haar navertelling.~A fellow learner recognised the three main points in her retelling.~زبان‌آموز دیگری سه نکتهٔ اصلی را در بازگویی او تشخیص داد.~Haar samenvatting behield de samenhang doordat zij selecteerde op functie in plaats van alleen op opvallende woorden.~Her summary retained coherence because she selected by function rather than merely by striking words.~خلاصه انسجام را حفظ کرد، چون انتخاب بر نقش استوار بود نه فقط واژه‌های برجسته.
90~Bij de tweede presentatie konden luisteraars de vragen later zelf beantwoorden.~After the second presentation, listeners could answer the questions themselves.~پس از ارائهٔ دوم، شنوندگان می‌توانستند خودشان پرسش‌ها را پاسخ دهند.~Het succes werd daarmee afgemeten aan wat luisteraars konden reconstrueren, niet uitsluitend aan zijn eigen vloeiende optreden.~Success was thus judged by what listeners could reconstruct, not solely by his fluent delivery.~موفقیت با بازسازی شنوندگان سنجیده شد، نه فقط بیان روان او.
91~De groep legde vast wanneer de uitzondering van toepassing was.~The group recorded when the exception applied.~گروه ثبت کرد استثنا چه زمانی برقرار است.~Gelijke regels werden pas eerlijker toegepast toen hun ongelijke gevolgen bespreekbaar waren.~Uniform rules became fairer in application only when their unequal effects could be discussed.~اجرای قواعد یکسان وقتی منصفانه‌تر شد که پیامدهای نابرابر قابل‌بحث شدند.
92~De jury publiceerde een korte uitleg bij de uitslag.~The jury published a short explanation with the result.~داوران توضیح کوتاهی همراه نتیجه منتشر کردند.~Vaste criteria namen alle subjectiviteit niet weg, maar begrensden de ruimte voor onzichtbare voorkeuren.~Fixed criteria did not remove all subjectivity, but limited room for hidden preferences.~معیار ثابت همهٔ ذهنیت را حذف نکرد، اما فضای ترجیح‌های پنهان را محدود کرد.
93~De spreker luisterde zonder meteen zijn bedoelingen te verdedigen.~The speaker listened without immediately defending his intentions.~گوینده گوش داد، بدون دفاع فوری از نیت خود.~Door het effect van de grap te erkennen, hoefde de ander niet eerst een verkeerde bedoeling te bewijzen.~Acknowledging the joke's effect meant the other person did not first have to prove bad intent.~پذیرفتن اثر شوخی باعث شد دیگری ناچار نباشد ابتدا نیت بد را اثبات کند.
94~De vereniging kon dankzij de vroege melding hulp bijzoeken.~The early notice allowed the association to seek extra help.~خبر زودهنگام به انجمن امکان داد کمک بیشتری پیدا کند.~Het bijstellen van de belofte herstelde voorspelbaarheid, terwijl het vasthouden eraan vooral onzekerheid zou hebben verlengd.~Revising the promise restored predictability, while clinging to it would mainly have prolonged uncertainty.~اصلاح وعده پیش‌بینی‌پذیری را برگرداند؛ پافشاری فقط ابهام را طولانی می‌کرد.
95~De foto's kregen beschrijvingen voordat ze elders werden bewaard.~The photographs received descriptions before being stored elsewhere.~پیش از نگهداری عکس‌ها در جای دیگر، برایشان توضیح نوشته شد.~Uitstel was hier geen besluiteloosheid, maar een manier om onomkeerbaar verlies eerst beter te beoordelen.~Delay here was not indecision but a way to assess irreversible loss more carefully first.~تأخیر اینجا بی‌تصمیمی نبود، بلکه راهی برای سنجش دقیق‌تر فقدان برگشت‌ناپذیر بود.
96~Reizigers kregen pas na de controle een definitieve datum.~Travellers received a definite date only after the inspection.~مسافران فقط پس از بررسی تاریخ قطعی گرفتند.~De boodschap verloor aan stelligheid maar won aan nauwkeurigheid doordat voorwaarden zichtbaar bleven.~The message became less categorical but more accurate because its conditions remained visible.~پیام قطعیت کمتری داشت اما دقیق‌تر شد، چون شرط‌ها روشن ماندند.
97~De lezers kregen ook de onderliggende bedragen te zien.~Readers were also shown the underlying amounts.~خوانندگان مبلغ‌های پایه را هم دیدند.~De presentatie werd controleerbaarder toen het visuele effect naast de werkelijke orde van grootte kon worden gelegd.~The presentation became more checkable when its visual effect could be compared with the actual magnitude.~وقتی اثر بصری با اندازهٔ واقعی قابل‌مقایسه شد، نمایش بررسی‌پذیرتر شد.
98~De moderator liet de jaartallen zichtbaar naast de cijfers zetten.~The moderator had the years visibly placed beside the figures.~گرداننده خواست سال‌ها روشن کنار ارقام نوشته شوند.~De schijnbare tegenstelling verdween pas toen duidelijk werd dat beide uitspraken een ander tijdvak betroffen.~The apparent contradiction disappeared only when it became clear that the statements concerned different periods.~تناقض ظاهری وقتی از بین رفت که تفاوت دوره‌های دو گفته روشن شد.
99~Bij het korte fragment kwam een link naar het volledige gesprek.~The short clip received a link to the full conversation.~کنار بخش کوتاه پیوند گفت‌وگوی کامل قرار گرفت.~De redactie behield een toegankelijke ingang, maar maakte de weggelaten argumentatieve ontwikkeling opnieuw bereikbaar.~The editors retained an accessible entry point while making the omitted development of the argument available again.~تحریریه ورودی ساده را حفظ کرد، اما روند استدلال حذف‌شده را دوباره در دسترس گذاشت.
100~De lezer koos ervoor verschillende bronnen te blijven volgen.~The reader chose to continue following several sources.~خواننده تصمیم گرفت همچنان چند منبع را دنبال کند.~Het onderscheid tussen een aannemelijk scenario en een zekere uitkomst werd belangrijker dan het aantal gepresenteerde cijfers.~Distinguishing a plausible scenario from a certain outcome mattered more than the number of figures presented.~تمایز سناریوی پذیرفتنی از نتیجهٔ قطعی مهم‌تر از تعداد ارقام ارائه‌شده شد.
'''
